### ISSUE TITLE
Data Update?

### ISSUE THREAD

**Issue by LePetitNewbie** [kyleskom/NBA-Machine-Learning-Sports-Betting#10]
Hi Kyle
        This looks really good. I tried running the code and it worked first time. Do I need to update the data in any ways or this is good to go for the rest of this season? 

FYI I have no coding experience so just trying to understand how it works. It looks great. Thanks for your work

Take care
Ol

**Comment by kyleskom** [comment]
It pulls the team data even time you run for the current day. The data is automatically updated.
