### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by ronpysui** [kyleskom/NBA-Machine-Learning-Sports-Betting#100]
Getting this ValueError

**------------------fanduel odds data------------------
Team Luka  (None) @ Team Scoot  (None)
Team Giannis  (None) @ Team LeBron  (None)
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "main.py", line 84, in main
    data, todays_games_uo, frame_ml, home_team_odds, away_team_odds = createTodaysGames(games, df, odds)
  File "main.py", line 51, in createTodaysGames
    games_data_frame = pd.concat(match_data, ignore_index=True, axis=1)
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate**
![image](https://user-images.githubusercontent.com/55932474/219921673-41bd896e-bae0-4079-8f34-431189f9af76.png)

**Comment by kyleskom** [comment]
Try doing a git pull on master branch

**Comment by victorpanitz** [comment]
Just faced the same here.

**Comment by kyleskom** [comment]
There's no games today. Let resist when there are games again to test.

**Comment by ronpysui** [comment]
still didn't work for me but that's okay, and have you ever thought of making a discord server or a group of some sort for this repo?

**Comment by MaxSokolich** [comment]
getting the same error too

**Comment by megler** [comment]
> There's no games today. Let resist when there are games again to test.

The all star game is today 2/19. Is the error because they aren't regular NBA teams?

I rolled back 2 commits and can overcome the concatenate error, but the odds do not populate on any sportsbook. I've checked Fanduel and there are odds for the game.

![image](https://user-images.githubusercontent.com/12972077/219963909-1c1635d3-2e2a-40c7-8a93-aa10eb304552.png)

![image](https://user-images.githubusercontent.com/12972077/219964012-e8f3d7dc-fe30-49e7-aa8a-10de7417670e.png)

**Comment by kyleskom** [comment]
#104

**Comment by kyleskom** [comment]
> still didn't work for me but that's okay, and have you ever thought of making a discord server or a group of some sort for this repo?

@ronpysui I have not considered a discord. Please use the discussion page here.

**Comment by megler** [comment]
you pushed the fix right as I caught the problem in Utils. Thanks for the fast response!

**Comment by kyleskom** [comment]
> > There's no games today. Let resist when there are games again to test.
> 
> The all star game is today 2/19. Is the error because they aren't regular NBA teams?
> 
> I rolled back 2 commits and can overcome the concatenate error, but the odds do not populate on any sportsbook. I've checked Fanduel and there are odds for the game.
> 
> ![image](https://user-images.githubusercontent.com/12972077/219963909-1c1635d3-2e2a-40c7-8a93-aa10eb304552.png)
> 
> ![image](https://user-images.githubusercontent.com/12972077/219964012-e8f3d7dc-fe30-49e7-aa8a-10de7417670e.png)

@megler The all star game is not something that can be trained on thus predicted.
