### ISSUE TITLE
Add more ML models

### ISSUE THREAD

**Issue by mile-ignjatovic** [kyleskom/NBA-Machine-Learning-Sports-Betting#102]
Some ideas:
- We can create a lot of different ML models that predict the outcome in different ways and combine them in the end to get the most accurate prediction like its already done with XGBoost and Neural network models
- News scrapers that use chatGPT to get a summary would also be a good thing (this could be a different app).
- Social media scraper with the same functionality  (this could be a different app).

**Comment by kyleskom** [comment]
Please add this to the discussions.
