### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by davidcamilo0710** [kyleskom/NBA-Machine-Learning-Sports-Betting#103]
Bro, did you really manage to get those precisions of 75% and 58%? I trained the models and the actual accuracies are 66% and 51%. and 51% makes a lot of sense, since that 58% is something very profitable in the over under.

**Comment by kyleskom** [comment]
I really did. It's been fairly long time since I trained those models. I can't guarantee what architecture I used or anything since its been so long.

**Comment by Skysafe64** [comment]
What can we do ? There are days when there are no good predictions, and I'm not talking about small deviations, I'm talking about big deviations. It's quite a shame, the potential here is huge. @kyleskom

**Comment by kyleskom** [comment]
@Skysafe64 I don't even know what you're really talking about. You're not going to get slam dunks every game. Maybe your expectations of what this is are whack. You're more then welcome to leave and create your own thing. This is a free open source project you can use or not use.

**Comment by Skysafe64** [comment]
> @Skysafe64 I don't even know what you're really talking about. You're not going to get slam dunks every game. Maybe your expectations of what this is are whack. You're more then welcome to leave and create your own thing. This is a free open source project you can use or not use.

It wasn't mean, I just wanted to say that lately the results given were clearly the opposite. But I had not seen the work of a user who can improve this project. Sorry if I misunderstood, I love this project :!

**Comment by Skysafe64** [comment]
@kyleskom Just a question, when before the matches should you watch the predictions? Just before the matches or as soon as the odds appear?

**Comment by kyleskom** [comment]
I usually track throughout the day and see if odds move into my favor more and make the bet when I think best is.

**Comment by Skysafe64** [comment]
@kyleskom Ok thank you that's good to know, I'm trying to study the results but it's quite complicated, how do you make your choice? In the collection of results available in the git, I wonder if you have counted absolutely all the predictions above 50%. Personally I studied those above 65%, maybe I'm not on the right track?

**Comment by kyleskom** [comment]
I would pick ones with high probability, good EV and checked lineups to account for any injuries
