### ISSUE TITLE
ModuleNotFoundError src+utils

### ISSUE THREAD

**Issue by madmax01** [kyleskom/NBA-Machine-Learning-Sports-Betting#110]
Hi,

when i start the  "python -m Get_Data.py" inside  src\Process-Data i get this error **ModuleNotFoundError: No module named 'src'**

when i change line 11 inside Get_Data.py
sys.path.insert(1, os.path.join(sys.path[0], '..'))
to
sys.path.insert(1, os.path.join(sys.path[0], '../utils'))

i get **ModuleNotFoundError: No module named 'Utils'**

why i'am doing wrong here?

**Comment by madmax01** [comment]
thx. whats the git command to get all the updates applied once downloaded the Master ?

**Comment by Calle1410** [comment]
Hey I have the same problem. Could you please be a bit more precise what I need to change in order to fix that? Thanks!
