### ISSUE TITLE
Is there an way to run those Python scripts for CUDA?

### ISSUE THREAD

**Issue by madmax01** [kyleskom/NBA-Machine-Learning-Sports-Betting#112]
when i do the public cuda test https://www.geeksforgeeks.org/running-python-script-on-gpu/

i get:

without GPU: 1.0266576000003624
with GPU: 0.18815099999937956
--------

when i use the machine-learning scripts  > my CPU 12C i7-1200KF jumps to 100%...

May interesting to see if works with numba

any way easy to convert it?

**Comment by kyleskom** [comment]
This is unfortunately a question I can't answer easily. I run on apple silicon Mac.
