### ISSUE TITLE
Google Collab Issue.

### ISSUE THREAD

**Issue by MetaUlya** [kyleskom/NBA-Machine-Learning-Sports-Betting#113]
When the "!python3 main.py -A -odds=fanduel" cell is run, the following output is given: 

2023-02-22 05:58:09.245415: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-02-22 05:58:09.245482: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (d7f872695620): /proc/driver/nvidia/version does not exist
2023-02-22 05:58:09.245923: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "/content/src/Predict/NN_Runner.py", line 10, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML')
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/load.py", line 155, in load
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py", line 202, in compile_args_from_training_config
    optimizer = optimizers.deserialize(optimizer_config)
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizers.py", line 95, in deserialize
    return deserialize_keras_object(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/generic_utils.py", line 659, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/generic_utils.py", line 556, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown optimizer: Custom>Adam. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root)._default_save_signature
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-0.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-0.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).__call__.trace_3
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_1
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_2
WARNING:tensorflow:Unresolved object in checkpoint: (root).call_and_return_all_conditional_losses.trace_3
WARNING:tensorflow:Unresolved object in checkpoint: (root).optimizer._update_step_xla
WARNING:tensorflow:Unresolved object in checkpoint: (root).signatures.serving_default
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-0.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-0.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-0.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-1.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-2.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.__call__.trace_0
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer_with_weights-3.call_and_return_all_conditional_losses.trace_0
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.

**Comment by davidhames123** [comment]
Hey mate - Try cloning this repo instead as it is updated. be sure too change it back once the master branch is patched however.

! git clone -b x86train https://github.com/nkgilley/NBA-Machine-Learning-Sports-Betting.git
