### ISSUE TITLE
Flask index html

### ISSUE THREAD

**Issue by SoccerCashUK** [kyleskom/NBA-Machine-Learning-Sports-Betting#123]
I'm trying to run the flask as to your instructions but I get error as it's saying then is no flask to run in the flask directory can you help please 
James

**Comment by JimCollinsDC** [comment]
pip install flask

**Comment by SoccerCashUK** [comment]
> pip install flask

Already have

**Comment by mendez97cr** [comment]
Are you running Python 3.8? make sure by type into CMD "Python". then
install all the pip installs again.

**Comment by JimCollinsDC** [comment]
"pip -r requirements.txt" should install everything at the same time rather than one-by-one.

**Comment by Zapors** [comment]
The instructions are not correct. I found that way to run Flask.
python3 -m flask --debug run
