### ISSUE TITLE
Flask: "ModuleNotFoundError: No module named 'pandas'"

### ISSUE THREAD

**Issue by JimCollinsDC** [kyleskom/NBA-Machine-Learning-Sports-Betting#125]
When I try to run the Flask version (flask --debug run) I get this error:
Traceback (most recent call last):
  File "C:\Projects\NBA-Machine-Learning-Sports-Betting\main.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Yes, pandas is installed. I'm running this in a venv if that helps.
If i run the code normally ( python main.py -xgb -odds=fanduel ) it works fine.

**Comment by mendez97cr** [comment]
Maybe you have more than one version of Python installed and the pandas
files got installed in the wrong one.

**Comment by JimCollinsDC** [comment]
Again, I'm using venv.

**Comment by JimCollinsDC** [comment]
You pointed me in the right direction, kinda. 
subprocess doesn't know/care about your virtual environment, it uses the python on the path. Solution?
change "cmd = ["python", "main.py", "-xgb", f"-odds={sportsbook}"] on line 27 to
to
cmd = ["../env/scripts/python", "main.py", "-xgb", f"-odds={sportsbook}"]
Voilà: 
![image](https://user-images.githubusercontent.com/16358167/221439546-5b3b0fbc-4cb3-41ee-a08c-eff24c25175b.png)

**Comment by kyleskom** [comment]
Awesome!
