### ISSUE TITLE
New data for google collab

### ISSUE THREAD

**Issue by BlakeBower** [kyleskom/NBA-Machine-Learning-Sports-Betting#131]
@nkgilley hey mate, do you know how we might be able to implement this seasons data while using google collab with the code you put out? cheers in advance

**Comment by Skysafe64** [comment]
> @nkgilley hey mate, do you know how we might be able to implement this seasons data while using google collab with the code you put out? cheers in advance

`!cd src/Process-Data && python -m Get_Data && python -m Create_Games
`

**Comment by tejrai13** [comment]
I've tried implementing this season's data, however its taking very long to retrain the model. Is there anyway to speed up the process or circumvent the model from being retrained everything?

**Comment by Marcfeitosa** [comment]
> > @nkgilley hey mate, do you know how we might be able to implement this seasons data while using google collab with the code you put out? cheers in advance
> 
> `!cd src/Process-Data && python -m Get_Data && python -m Create_Games `

Sorry for the ignorance, but where should this line go in the code?
Cheers
