### ISSUE TITLE
python3 main.py -xgb -odds=fanduel

### ISSUE THREAD

**Issue by SoccerCashUK** [kyleskom/NBA-Machine-Learning-Sports-Betting#140]
Hi I wonder if you can help
I run the command python3 main.py -xgb -odds=fanduel, even tried draftkings
And I get loads of zeros , and none for the Over 
Thanks
![20230312_112817](https://user-images.githubusercontent.com/43697092/224541775-d9ac3c06-1e66-4d6e-886c-29e36b578ef4.jpg)

**Comment by marine1983boots** [comment]
If you are in the UK try changing the bookie to bet365. It looks like the website it scrapes odds from geo locates you.

**Comment by SoccerCashUK** [comment]
> If you are in the UK try changing the bookie to bet365. It looks like the website it scrapes odds from geo locates you.
> 
> python3 main.py -xgb -odds=bet365

Thanks that worked, Now trying to run flask but not working any ideal
James

**Comment by marine1983boots** [comment]
I think its the same problem. Flask is running with the standard bookies which wont return any data. I've not used the flask thing,.
