### ISSUE TITLE
Issue with final results showing up

### ISSUE THREAD

**Issue by jrlarke** [kyleskom/NBA-Machine-Learning-Sports-Betting#15]
First off, what an awesome model! Downloaded this last night and it worked great.  My only issue is with the format on the final results.  The coloring isn't showing up so the format is weird and while I can interpret it eventually it's not ideal.  I'll attach a screenshot

![Capture2](https://user-images.githubusercontent.com/20980106/139310607-8a5f1bc7-1450-46fe-81e8-2ab97e416e0e.PNG)

Is there anyway we could get a spreadsheet output of the results vs the console output?

Also, any plans to apply this to any other sports?

**Comment by kyleskom** [comment]
Awesome thank for being the Windows tester. Im going to go ahead and merge these changes into master! @jrlarke
