### ISSUE TITLE
MLB?

### ISSUE THREAD

**Issue by JP23000** [kyleskom/NBA-Machine-Learning-Sports-Betting#150]
How would I go about modifying this for the upcoming MLB season?

**Comment by Marcfeitosa** [comment]
Good question

**Comment by kyleskom** [comment]
This would essentially require an entire re-write. Please continue this discussion in the Discussions tab.

**Comment by JP23000** [comment]
Will do.

I assumed that was the case and was off hand crossing my fingers hoping the
response was, “we have actually already started doing this”. 😂

I’ll submit it through the discussion posts.

I can also fumble my way through it and ask for pointers and directions
when I get stuck.

I completed that applied data science certificate from MIT’s professional
program…. But that was my first real exposure to data science and python
outside the basic level stuff I used as an engineer at ASML.

Thanks!

John
