### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Isen1232** [kyleskom/NBA-Machine-Learning-Sports-Betting#152]
2023-03-15 22:05:40.531626: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-15 22:05:41.698028: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-03-15 22:05:43.537379: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

help?

**Comment by betevents** [comment]
upgrade tensorflow to the latest
pip install tensorflow==2.12.0.rc1

**Comment by Isen1232** [comment]
Tried it, still gives me the same response

**Comment by betevents** [comment]
can you try installing the nightly build? unsure which one would work better but they are not very stable at times
pip install tf-nightly

how do you run the script?

**Comment by kyleskom** [comment]
Check python version too. I use 3.9

**Comment by ebrinkster** [comment]
You can also build from source with CUDA support enabled if you're having trouble with provided packages -- https://www.tensorflow.org/install/source

**Comment by Isen1232** [comment]
I tried install nighly but it still gives me the same response. I use python version 3.9.16

**Comment by Isen1232** [comment]
I noticed now while trying to install nighly, i got this: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.11.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.22.1 which is incompatible.
tensorflow-metadata 1.12.0 requires protobuf<4,>=3.13, but you have protobuf 4.22.1 which is incompatible.
tensorboard 2.11.2 requires protobuf<4,>=3.9.2, but you have protobuf 4.22.1 which is incompatible.
tensorboard 2.11.2 requires tensorboard-data-server<0.7.0,>=0.6.0, but you have tensorboard-data-server 0.7.0 which is incompatible.

**Comment by betevents** [comment]
you need the versions between the ranges it requires. it's probably the issue with a non pre built version of tensorflow but i use the nightly versions never had problems with

just try to install those versions, i have this
tensorboard 2.12.0
tensorflow-metadata 1.12.0
protobuf 4.22.1
tensorboard-data-server 0.7.0

can you upgrade your tensorflow to 2.12.0 without the rc1?
pip install tensorflow==2.12.0
or
pip3 install tensorflow==2.12.0
or
python3 -m pip install tensorflow==2.12.0
