### ISSUE TITLE
no predictions 

### ISSUE THREAD

**Issue by palachiinka** [kyleskom/NBA-Machine-Learning-Sports-Betting#158]
After I enter the numbers I don;t get info :

Orlando Magic vs Washington Wizards: 235
Orlando Magic odds: 320
Washington Wizards odds: -417
Atlanta Hawks vs Detroit Pistons: 240 
Atlanta Hawks odds: 300
Detroit Pistons odds: -115
Brooklyn Nets vs Cleveland Cavaliers: 220
Brooklyn Nets odds: 103
Cleveland Cavaliers odds: -150
New Orleans Pelicans vs San Antonio Spurs: 240
New Orleans Pelicans odds: -150
San Antonio Spurs odds: 153
Sacramento Kings vs Boston Celtics: 238
Sacramento Kings odds: -140
Boston Celtics odds: 150
LA Clippers vs Oklahoma City Thunder: 245
LA Clippers odds: 160
Oklahoma City Thunder odds: -132

**Comment by kyleskom** [comment]
Run with
`python main.py -A -odds=draftkings`
