### ISSUE TITLE
OSError: no file or directory found at models/NN_models/trained-model-ML

### ISSUE THREAD

**Issue by Brh5194** [kyleskom/NBA-Machine-Learning-Sports-Betting#163]
![image](https://user-images.githubusercontent.com/129190138/228656158-90fb3f79-b69c-42eb-a96d-88a8ac565f24.jpg)
Hey! I’ve been trying to get this to work on colab but I keep stumbling across this error 
“OSError: no file or directory found at models/NN_models/trained-model-ML” when I run python3 main.py -A -odds=fanduel 

any help is much appreciated

**Comment by mriphonecanada** [comment]
Same here....

**Comment by kyleskom** [comment]
Make sure you are in the correct Directory

**Comment by mriphonecanada** [comment]
> Make sure you are in the correct Directory

Yes....absolutely.

After some tweaking....I get this now.

![image](https://user-images.githubusercontent.com/127436687/229223759-22c4d468-f2c9-4463-88d6-49b4411ce884.png)

**Comment by mike-bostedt** [comment]
I was able to get past the above error by downgrading tensorflow from v=2.12 to v=2.11. 

If v=2.11 is in fact the latest supported version we should probably highlight that somewhere in the readme.

**Comment by CeeeeJay** [comment]
> I was able to get past the above error by downgrading tensorflow from v=2.12 to v=2.11.
> 
> If v=2.11 is in fact the latest supported version we should probably highlight that somewhere in the readme.

How did you even downgrade from 2.12 to 2.11 in the first place?

**Comment by Hepziba97** [comment]
which keras version did you use, because am getting this error- modulenotfounderror: tensorflow.keras.models
