### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by ShenMcConnell** [kyleskom/NBA-Machine-Learning-Sports-Betting#167]
Im not sure why I'm getting this error I can see the requirements file is downloaded, but I'm not sure why it can't access it.

**Comment by ShenMcConnell** [comment]
I'm using google collab is there a suggested one I should be using?

**Comment by kyleskom** [comment]
run `pwd` and make sure your in the root.
