### ISSUE TITLE
Does not predict future matches, but shows past matches

### ISSUE THREAD

**Issue by obtim** [kyleskom/NBA-Machine-Learning-Sports-Betting#17]
Downloaded and launched today - 01.11.2021 at 13.55(UTC). 
The script prompts you to fill in the data for:
Dallas Mavericks vs Sacramento Kings
Charlotte Hornets vs Portland Trail Blazers
Los Angeles Lakers vs Houston Rockets
Milwaukee Bucks vs Utah Jazz 
Brooklyn Nets vs Detroit Pistons.
All of these games are already over. 
How do I run predictions for upcoming games?

**Comment by kyleskom** [comment]
The games for that day are updated around noon EST. Please run between then games start.

**Comment by obtim** [comment]
> The games for that day are updated around noon EST. Please run between then games start.

Please, add this information to main page. Thanks!
