### ISSUE TITLE
python -m Get_Odds_Data "list index out of range"

### ISSUE THREAD

**Issue by szocpaul** [kyleskom/NBA-Machine-Learning-Sports-Betting#170]
Can you please check this error message? It was during Get_Odds_Data.

Error:

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:40<00:00,  1.30s/it]
  0%|                                                                                                                                                 | 0/9 [00:00<?, ?it/sAn error occurred: list index out of range                                                                                                     | 1/9 [00:40<05:21, 40.17s/it]
 23%|██████████████████████████████▋                                                                                                         | 7/31 [00:26<01:39,  4.13s/itAn error occurred: list index out of range
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:46<00:00,  3.45s/it]
                                                                                                                                                                           An error occurred: list index out of range                                                                                                     | 2/9 [02:27<09:15, 79.41s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:46<00:00,  3.43s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:46<00:00,  3.42s/it]
 33%|█████████████████████████████████████████████▋                                                                                           | 3/9 [04:13<09:10, 91.71s/itNo fanduel odds data found for game: {'date': '2023-02-18T00:00:00+00:00', 'status': 'Final', 'home_team': 'Team Dwyane ', 'home_team_loc': 'Team Dwyane', 'home_team_abbr': 'DWYANE', 'home_team_rank': -1, 'away_team': 'Team Ryan ', 'away_team_loc': 'Team Ryan', 'away_team_abbr': 'RYAN', 'away_team_rank': -1, 'home_score': 0, 'away_score': 0, 'home_spread': {}, 'home_spread_odds': {}, 'away_spread': {}, 'away_spread_odds': {}, 'under_odds': {}, 'over_odds': {}, 'total': {}, 'home_ml': {}, 'away_ml': {}}
No fanduel odds data found for game: {'date': '2023-02-18T02:00:00+00:00', 'status': 'Final', 'home_team': 'Team Deron ', 'home_team_loc': 'Team Deron', 'home_team_abbr': 'DERON', 'home_team_rank': -1, 'away_team': 'Team Pau ', 'away_team_loc': 'Team Pau', 'away_team_abbr': 'PAU', 'away_team_rank': -1, 'home_score': 25, 'away_score': 40, 'home_spread': {}, 'home_spread_odds': {}, 'away_spread': {}, 'away_spread_odds': {}, 'under_odds': {}, 'over_odds': {}, 'total': {}, 'home_ml': {}, 'away_ml': {}}
No fanduel odds data found for game: {'date': '2023-02-18T03:00:00+00:00', 'status': 'Final', 'home_team': 'Team Pau ', 'home_team_loc': 'Team Pau', 'home_team_abbr': 'PAU', 'home_team_rank': -1, 'away_team': 'Team Joakim ', 'away_team_loc': 'Team Joakim', 'away_team_abbr': 'JOAKIM', 'away_team_rank': -1, 'home_score': 25, 'away_score': 20, 'home_spread': {}, 'home_spread_odds': {}, 'away_spread': {}, 'away_spread_odds': {}, 'under_odds': {}, 'over_odds': {}, 'total': {}, 'home_ml': {}, 'away_ml': {}}
                                                                                                                                                                           An error occurred: list index out of range
 55%|██████████████████████████████████████████████████████████████████████████                                                             | 17/31 [01:04<00:56,  4.01s/itNo fanduel odds data found for game: {'date': '2023-02-19T20:00:00+00:00', 'status': 'Final', 'home_team': 'Team Scoot ', 'home_team_loc': 'Team Scoot', 'home_team_abbr': 'SCOOT', 'home_team_rank': -1, 'away_team': 'Team Luka ', 'away_team_loc': 'Team Luka', 'away_team_abbr': 'LUKA', 'away_team_rank': -1, 'home_score': 0, 'away_score': 0, 'home_spread': {}, 'home_spread_odds': {}, 'away_spread': {}, 'away_spread_odds': {}, 'under_odds': {}, 'over_odds': {}, 'total': {}, 'home_ml': {}, 'away_ml': {}}
No fanduel odds data found for game: {'date': '2023-02-20T01:30:00+00:00', 'status': 'Final', 'home_team': 'Team LeBron ', 'home_team_loc': 'Team LeBron', 'home_team_abbr': 'LEBRON', 'home_team_rank': -1, 'away_team': 'Team Giannis ', 'away_team_loc': 'Team Giannis', 'away_team_abbr': 'GIANNI', 'away_team_rank': -1, 'home_score': 175, 'away_score': 184, 'home_spread': {}, 'home_spread_odds': {}, 'away_spread': {}, 'away_spread_odds': {}, 'under_odds': {}, 'over_odds': {}, 'total': {}, 'home_ml': {}, 'away_ml': {}}
                                                                                                                                                                           An error occurred: list index out of range
 61%|██████████████████████████████████████████████████████████████████████████████████▋                                                    | 19/31 [01:07<00:35,  3.00s/itAn error occurred: list index out of range
 65%|███████████████████████████████████████████████████████████████████████████████████████                                                | 20/31 [01:08<00:24,  2.24s/itAn error occurred: list index out of range
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:30<00:00,  2.93s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:50<00:00,  3.57s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 147418.85it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 163141.06it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 174060.81it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [09:20<00:00, 62.33s/it]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [09:21<00:00, 561.02s/it]

**Comment by mriphonecanada** [comment]
Yes...after most recent update...getting same error.
