### ISSUE TITLE
New models not being used

### ISSUE THREAD

**Issue by tjones-commits** [kyleskom/NBA-Machine-Learning-Sports-Betting#171]
in src/Predict/XGBoost_Runner.py on lines 14 and 16 are where it selects which trained model to use. There are hardcoded file names there. 

Models/XGBoost_Models/XGBoost_68.6%_ML-2.json
Models/XGBoost_Models/XGBoost_54.8%_UO-8.json

When new models are trained they are saved to the Models directory but they never get used because these two hardcoded ones are always used for the predictions. To use the new models I would need to update the path or move the files and rename them manually.

I'm not sure if this is deliberate design decision or something that should be fixed.

**Comment by kyleskom** [comment]
These are the correct models

**Comment by tjones-commits** [comment]
ok thanks. 

So if I run the module at NBA-Machine-Learning-Sports-Betting/src/Train-Models/XGBoost_Model_ML.py and create a new model I should move the new model to the Models/XGBoost_Models directory and then update the hardcoded values manually?
