### ISSUE TITLE
Getting this error when trying to run the python3 main.py -xgb -odds=<sportsbook> command

### ISSUE THREAD

**Issue by lkilbride5** [kyleskom/NBA-Machine-Learning-Sports-Betting#177]
![code error](https://user-images.githubusercontent.com/129338887/230241337-d12f264e-d1b7-472c-9539-5c50abb665fc.PNG)

I am still able to get full odds and predictions with fanduel, but I get the error no matter which sportsbook I try to use. Is this affecting my fanduel predictions? Is there anyway I can modify the stack to get rid of that error and hopefully be able to test this on other sportsbooks? I greatly appreciate any input.

**Comment by kyleskom** [comment]
I think this is a coda issue and using windows. Also check tensorflow version 2.11.0
