### ISSUE TITLE
Some problems with XGB predictions.

### ISSUE THREAD

**Issue by eSpadaMaddyS** [kyleskom/NBA-Machine-Learning-Sports-Betting#178]
Hey

I was checking the results of this project for some days. I saw results like:
![image](https://user-images.githubusercontent.com/113463164/230667272-aa1a23a9-b577-481a-8851-cf40b32dc92f.png)

But a week ago i got this:
![image](https://user-images.githubusercontent.com/113463164/230666988-3d811663-c8fb-4c99-94f5-928ba317a0b8.png)

I don't receive XGB predictions, just parse odds from sportsbook. I can't found the type of my problem.

Can you describe me the way i should check out?
I have Python 3.8 and all versions from requirements.txt+tensorflow==2.11.0.
I don't receive any messages about errors. Just odds data but nothing else.

**Comment by kyleskom** [comment]
I use python 3.9. Maybe that would fix it?

**Comment by eSpadaMaddyS** [comment]
I installed Python 3.9. Results are the same. 
It's actually very strange. It seems that the program simply stops after the coefficients are output. Data parsing goes perfectly, but it's as if the prediction model itself doesn't even start.

**Comment by eSpadaMaddyS** [comment]
As a result, the program is working today, but now NN forecast gives an error. Apparently I'll have to look for more information on the Internet

![image](https://user-images.githubusercontent.com/113463164/230733907-d5070886-51f8-48ae-a894-6f18c8e2d769.png)
