### ISSUE TITLE
I'm on PC running 2.11.0

### ISSUE THREAD

**Issue by Hepziba97** [kyleskom/NBA-Machine-Learning-Sports-Betting#182]
I'm on PC running 2.11.0

_Originally posted by @mike-bostedt in https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/180#issuecomment-1501179269_
            
I'm getting this error after i installed tensorflow 2.11.0:
    from tensorflow.keras.models import load_model
ModuleNotFoundError: No module named 'tensorflow.keras'

**Comment by kyleskom** [comment]
Try
`pip install keras==2.11.0`
