### ISSUE TITLE
No games found.

### ISSUE THREAD

**Issue by NikitaSmirnov** [kyleskom/NBA-Machine-Learning-Sports-Betting#184]
Greetings, I have installed all the specified packages.

Next, from the project folder, I entered the following commands
$ pip3 install -r requirements.txt
$ python3 main.py -xgb -odds=fanduel

And I got this answer in the console:
No games found.

I will be grateful if you help with the problem.

![image](https://user-images.githubusercontent.com/17338945/230989822-5fc17773-b8e4-45fc-95a7-cf62dcb04acb.png)

**Comment by NikitaSmirnov** [comment]
Can i change the date in programme?

**Comment by kyleskom** [comment]
We do not have that capability.

**Comment by Fastlane86** [comment]
If you want games for the next day. You can just change your system clock/date. I’ve done it. It works. Odds won’t be up to date though.
