### ISSUE TITLE
stats.nba.com data_url problem

### ISSUE THREAD

**Issue by impulsecorp** [kyleskom/NBA-Machine-Learning-Sports-Betting#19]
The data_url you use in main.py does not seem to work:
data_url = 'https://stats.nba.com/stats/leaguedashteamstats?' \
           'Conference=&DateFrom=&DateTo=&Division=&GameScope=&' \
           'GameSegment=&LastNGames=0&LeagueID=00&Location=&' \
           'MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&' \
           'PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&' \
           'PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&' \
           'Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&' \
           'StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision='

When I try it running your program it just hangs, and same when when I enter this into my browser:
https://stats.nba.com/stats/leaguedashteamstats?Conference=&DateFrom=&DateTo=&Division=&GameScope=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2021-22&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=

**Comment by kyleskom** [comment]
Will take a look at this in some time. Just got a new m1 MacBook and haven't been able to fully get this running yet.

**Comment by impulsecorp** [comment]
The problem has nothing to do with your program though. The url you are using for the data is https://stats.nba.com/stats/leaguedashteamstats  and that does not work, even outside of your program.  So that means either nba.com changed the url structure or they no longer offer that data.  

I have your program working in general, but it can't make predictions without a source of data. I can try to find a new data source but thought maybe there was a more simple solution that you could figure out.

**Comment by impulsecorp** [comment]
The problem may be just on my server for some reason. It worked fine for my programmer on his server (he is in a different country). I am going to setup a new server with another host and try it there.

**Comment by impulsecorp** [comment]
The problem seems to be that stats.nba.com data feed url only works from certain countries. I tried from 2 different servers on 2 different hosts and it did not work on either of them.  One server was in the USA, one in Canada. It works fine from my programmer's computer in Bulgaria.

**Comment by kyleskom** [comment]
That's very weird. Im located in US and was working for me.

**Comment by impulsecorp** [comment]
Yes, strange. The 2 dedicated Linux servers I tried it on were through ovh.com (Canada) and AWS Lightsail (USA).

**Comment by kyleskom** [comment]
Sorry I can't provide any help on this. If you figure this out do let me know.
