### ISSUE TITLE
Google Colab ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by igelmigel4** [kyleskom/NBA-Machine-Learning-Sports-Betting#192]
fatal: destination path 'NBA-Machine-Learning-Sports-Betting' already exists and is not an empty directory.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
python3: can't open file '/content/main.py': [Errno 2] No such file or directory

**Comment by julianxv** [comment]
Use this line instead:

pip3 install -r /content/NBA-Machine-Learning-Sports-Betting/requirements.txt

**Comment by poult-lab** [comment]
> Use this line instead:
> 
> pip3 install -r /content/NBA-Machine-Learning-Sports-Betting/requirements.txt

even I rely on this way to install the packages successfully, but I still confused. I already mounted the google cloud successfully, I cam import the python file as well. but I am not able to install package directly. I have to add the path of package file.
