### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by analfarmer420** [kyleskom/NBA-Machine-Learning-Sports-Betting#193]
<img width="909" alt="Bildschirm­foto 2023-04-19 um 21 28 18" src="https://user-images.githubusercontent.com/131298884/233180063-9a010d0f-1bc8-4e1d-b16a-e292803d9a51.png">
Can someone help me?

**Comment by julianxv** [comment]
Use this line instead:

pip3 install -r /content/NBA-Machine-Learning-Sports-Betting/requirements.txt

**Comment by julianxv** [comment]
> Use this line instead:
> 
> pip3 install -r /content//content/NBA-Machine-Learning-Sports-Betting/requirements.txt

or a better change. Change the ! cd /content/NBA-Machine-Learning-Sports-Betting command before to:

%cd NBA-Machine-Learning-Sports-Betting
