### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed

### ISSUE THREAD

**Issue by xhaeusslerx** [kyleskom/NBA-Machine-Learning-Sports-Betting#194]
Hello together,

I get the following error when executing the code.

! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
! cd NBA-Machine-Learning-Sports-Betting
! pip3 install -r NBA-Machine-Learning-Sports-Betting/requirements.txt

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.11.0 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.

I tried it with the following and now I receive match bet results.

! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
! cd NBA-Machine-Learning-Sports-Betting
! pip3 install -r NBA-Machine-Learning-Sports-Betting/requirements.txt
! pip install tensorflow==2.12.0rc0

Unfortuantely I didnt receive the neuronal network model prediction. Only the XGBoost

**Comment by kyleskom** [comment]
Should be fixed now.
