### ISSUE TITLE
ModuleNotFoundError: No module named 'sbrscrape'

### ISSUE THREAD

**Issue by RABAUZ** [kyleskom/NBA-Machine-Learning-Sports-Betting#195]
Hello,

actually i do have the following problem:

![image](https://user-images.githubusercontent.com/131355459/233333349-6662e791-9532-491a-95fd-c18401ce86d9.png)

Anyone here has any ideas how to fix this?

Thanks in advance!

**Comment by kyleskom** [comment]
`pip install sbrscrape`
