### ISSUE TITLE
Google Colab Error: pip's dependency resolver does not currently take into account all the packages that are installed.

### ISSUE THREAD

**Issue by GERThomasAI** [kyleskom/NBA-Machine-Learning-Sports-Betting#197]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.11.0 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.
Successfully installed colorama-0.4.6 keras-2.11.0 numpy-1.24.2 openpyxl-3.1.1 requests-2.28.2 sbrscrape-0.0.6 scikit-learn-1.2.1 tqdm-4.64.1 xgboost-1.7.4
python3: can't open file '/content/main.py': [Errno 2] No such file or directory

**Comment by xhaeusslerx** [comment]
I have the same problem reagrding the dependencys

**Comment by Leandrobeat** [comment]
i have some problem

**Comment by kyleskom** [comment]
Should be fixed now.
