### ISSUE TITLE
Google Colab ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. AND WARNING: The following packages were previously imported in this runtime:   [numpy] You must restart the runtime in order to use newly installed versions.

### ISSUE THREAD

**Issue by andrisbk** [kyleskom/NBA-Machine-Learning-Sports-Betting#199]
I am getting these 2 Problems when using Google Colab

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires keras<2.13,>=2.12.0, but you have keras 2.11.0 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.

AND

WARNING: The following packages were previously imported in this runtime:
  [numpy]
You must restart the runtime in order to use newly installed versions.

Can somebody help?

**Comment by kyleskom** [comment]
Should be fixed now.
