### ISSUE TITLE
Pulling data from current season 2021-22 

### ISSUE THREAD

**Issue by HalluxX** [kyleskom/NBA-Machine-Learning-Sports-Betting#20]
Is there a way to pull data in from the current season 2021-22? Sorry for the basic question, appreciate any insights you can provide

**Comment by kyleskom** [comment]
So it pulls in the current stats for all teams daily for current season, just hasn't been trained on data from this season. If you'd like to pull in that data to train with, you can use /src/Process-Data/

**Comment by HalluxX** [comment]
Okay, thanks for the quick response, appreciate it.
