### ISSUE TITLE
RuntimeWarning: Unexpected end-group tag: Not all data was converted

### ISSUE THREAD

**Issue by XiangjunWu** [kyleskom/NBA-Machine-Learning-Sports-Betting#205]
I get this RuntimeWarning immediately after I started the program:

![grafik](https://user-images.githubusercontent.com/91340627/233744370-4ff2e66a-0314-461a-9d78-bc2d574bcfb0.png)

Is this affecting the outcome of the prediction? Can someone please send me his result to compare?

**Comment by kyleskom** [comment]
Nope thats just a tensorflow warning. No issues.
