### ISSUE TITLE
No games found

### ISSUE THREAD

**Issue by Giant2424** [kyleskom/NBA-Machine-Learning-Sports-Betting#217]
Used this code:
! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
%cd NBA-Machine-Learning-Sports-Betting
! pip3 install -r requirements.txt
! python3 main.py -xgb -odds=fanduel

**Comment by chriseling** [comment]
Try it again or with a different odds provider like draftkings

! python3 main.py -xgb -odds draftkings

Best,
Chris
