### ISSUE TITLE
Programming Idiot

### ISSUE THREAD

**Issue by GhoTim** [kyleskom/NBA-Machine-Learning-Sports-Betting#220]
Hey im really new to all that and dont understand everything.
I get this Error when im trying to use it with googlecollab and i dont know how to fix it despite reading the issues from others about the same problem.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
python3: can't open file '/content/main.py': [Errno 2] No such file or directory
Is there any possibility someone can explain it to me for dummies or is there a video of how to set it up?

I would love a Respone and thanks in advance
Sincerly Tim

**Comment by z1mAli** [comment]
Same problem here
