### ISSUE TITLE
ERROR: No matching distribution found for tensorflow==2.6.0

### ISSUE THREAD

**Issue by Araquiel666** [kyleskom/NBA-Machine-Learning-Sports-Betting#225]
Could someone possibly take a look at the error. 

I use Colab. 
The following code was used: 
! git clone -b x86train https://github.com/nkgilley/NBA-Machine-Learning-Sports-Betting.git
! %cd NBA-Machine-Learning-Sports-Betting
! !ls
! pip3 install -r /content/NBA-Machine-Learning-Sports-Betting/requirements.txt
! python3 main.py -xgb -odds=fanduel

Complete error message: 
ERROR: Could not find a version that satisfies the requirement tensorflow==2.6.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0)
ERROR: No matching distribution found for tensorflow==2.6.0

Thanks for your help.

**Comment by kyleskom** [comment]
Run `pip install  tensorflow==2.11.0`
