### ISSUE TITLE
Google Colab working Code?

### ISSUE THREAD

**Issue by HiddenRaichuBots** [kyleskom/NBA-Machine-Learning-Sports-Betting#229]
Ive tried many things but theres always a new issue when im trying to set this up with google colab.

Can someone who set this up with **google colab** paste their **working code** in here?
Thanks for your replys.

(i dont know how all of this works)

**Comment by kyleskom** [comment]
The code from the repo works, just tested it. What errors are you seeing

**Comment by onlyadamscott** [comment]
I've run it out of the box in Colab, straight python in Windows, and in Docker. All good on current repo.

**Comment by onlyadamscott** [comment]
The Colab takes a little bit of reverse engineering and reading the code but it works.

**Comment by fciaf420** [comment]
Can someone please share the Colab exactly how it works Sent from my iPhoneOn Apr 29, 2023, at 8:33 PM, onlyadamscott ***@***.***> wrote:﻿
The Colab takes a little bit of reverse engineering and reading the code but it works.

**Comment by kyleskom** [comment]
Actually try now. I updated the notebook.

**Comment by HiddenRaichuBots** [comment]
> Actually try now. I updated the notebook.
thanks its working.
