### ISSUE TITLE
Google Colab Error: WARNING: The following packages were previously imported in this runtime:   [numpy]

### ISSUE THREAD

**Issue by Araquiel666** [kyleskom/NBA-Machine-Learning-Sports-Betting#236]
Hello, 

I have used the following code and am now getting the above error.

Code: 
! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
! cd NBA-Machine-Learning-Sports-Betting
! pip3 install -r NBA-Machine-Learning-Sports-Betting/requirements.txt
! pip install tensorflow==2.12.0rc0

I have now tried several times to perform the restart without success. 

Please for support. Thanks:

**Comment by kyleskom** [comment]
Just a warning.
