### ISSUE TITLE
Help interpreting results

### ISSUE THREAD

**Issue by tyroneschiff** [kyleskom/NBA-Machine-Learning-Sports-Betting#24]
OK, I was able to generate results for 1.17.2022. Can someone please help me interpret this output especially as it relates to the Expected Value calculations.

Thank you!

---------------XGBoost Model Predictions---------------
Atlanta Hawks vs Milwaukee Bucks (65.8%): UNDER 233.5 (54.2%)
Memphis Grizzlies (62.0%) vs Chicago Bulls: UNDER 225.5 (60.1%)
Orlando Magic vs Portland Trail Blazers (69.6%): OVER 193.5 (69.8%)
Los Angeles Lakers vs Utah Jazz (66.6%): OVER 230.5 (51.2%)
Miami Heat (69.5%) vs Toronto Raptors: UNDER 208.5 (53.7%)
Cleveland Cavaliers (60.3%) vs Brooklyn Nets: UNDER 222.5 (61.2%)
LA Clippers (67.4%) vs Indiana Pacers: OVER 209.5 (59.0%)
San Antonio Spurs vs Phoenix Suns (80.0%): UNDER 242.5 (73.8%)
New York Knicks vs Charlotte Hornets (55.9%): OVER 214.5 (67.8%)
Washington Wizards vs Philadelphia 76ers (50.9%): UNDER 221.5 (59.2%)
Boston Celtics (70.3%) vs New Orleans Pelicans: UNDER 213.5 (54.6%)
Dallas Mavericks (82.9%) vs Oklahoma City Thunder: UNDER 215.5 (67.5%)
--------------------Expected Value---------------------
Atlanta Hawks EV: -7.78
Milwaukee Bucks EV: -1.24
Memphis Grizzlies EV: -20.22
Chicago Bulls EV: 42.32
Orlando Magic EV: -34.74
Portland Trail Blazers EV: 19.39
Los Angeles Lakers EV: -1.42
Utah Jazz EV: -6.78
Miami Heat EV: -10.6
Toronto Raptors EV: 9.69
Cleveland Cavaliers EV: -7.91
Brooklyn Nets EV: 1.14
LA Clippers EV: 15.46
Indiana Pacers EV: -29.81
San Antonio Spurs EV: -61.04
Phoenix Suns EV: 49.65
New York Knicks EV: -25.5
Charlotte Hornets EV: 22.99
Washington Wizards EV: 0.58
Philadelphia 76ers EV: -8.32
Boston Celtics EV: 8.31
New Orleans Pelicans EV: -25.77
Dallas Mavericks EV: -9.6
Oklahoma City Thunder EV: 28.52

**Comment by kyleskom** [comment]
So for the first part it'll give the percent chance of that team winning. Same thing for under / overs. Expected value below include the odds in the percent chance to win. For best results use predictions with positive expected values. Please note this isn't a win all approach and just extra info in helping make decisions. There is still risk involved.
