### ISSUE TITLE
Error: "No games found."

### ISSUE THREAD

**Issue by matiasstornini** [kyleskom/NBA-Machine-Learning-Sports-Betting#243]
hello, install:
$ git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
$cd NBA-Machine-Learning-Sports-Betting
$ pip3 install -r requirements.txt
$ python3 main.py -xgb -odds=fanduel
in colab, but when running I get the error: No games found.
What fault do I have?

**Comment by P1stus** [comment]
Reisntall he updated the code. Justs pull it again with https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git

**Comment by matiasstornini** [comment]
fixed, it was an error in the project where I installed it
