### ISSUE TITLE
Type Error in Kelly_Critereon.py

### ISSUE THREAD

**Issue by JasperShoe** [kyleskom/NBA-Machine-Learning-Sports-Betting#248]
File "/Users/.../NBA-Machine-Learning-Sports-Betting/src/Utils/Kelly_Criterion.py", line 5, in american_to_decimal
    if american_odds >= 100:
TypeError: '>=' not supported between instances of 'str' and 'int'

Fix: 
Change home_team_odds[count] to int(home_team_odds[count])
Change away_team_odds[count] to int(away_team_odds[count])

**Comment by Ambrose997** [comment]
Huh? Where is home_team_odds?

**Comment by xalppt** [comment]
this method does not seem to fix the issue

**Comment by godlike007322** [comment]
i still have the problem

**Comment by kyleskom** [comment]
There are no games. Its trying to get odds for games that don't exist yet, try again when the season starts.
