### ISSUE TITLE
Train Model on Current Season

### ISSUE THREAD

**Issue by Emillzz45** [kyleskom/NBA-Machine-Learning-Sports-Betting#25]
Any insight for beginners how to consistently train the model with new data for the current season? 

Is the players stats and teams stats automatically updated from the last day?
How can I feed the data even more information?

Any ideas on converting existing model to NCAAB?

**Comment by kyleskom** [comment]
Training new data isn't super intuitive. I should work on that and make it easier. As for the predictions the data is pulled and updated for the teams stats daily. As this pulls directly from the NBA stats website changing to NCAAB isn't super easy but the ideas from this could be applied.

**Comment by Emillzz45** [comment]
I think doing a per quarter based O/U and ML could be a good addition as well.

**Comment by obtim** [comment]
> Training new data isn't super intuitive. I should work on that and make it easier. As for the predictions the data is pulled and updated for the teams stats daily. As this pulls directly from the NBA stats website changing to NCAAB isn't super easy but the ideas from this could be applied.

Is it possible to set the project output to a file to collect the results of the forecasts for any period?

**Comment by kyleskom** [comment]
@obtim As of right now no. Willing to accept pull requests for it ;)
