### ISSUE TITLE
Different result without -odds

### ISSUE THREAD

**Issue by AllInOneYT** [kyleskom/NBA-Machine-Learning-Sports-Betting#253]
I don't understand why am I getting different result with the exact same data?

**1**
`python3 main.py -xgb -odds=fanduel -kc`
```
------------------fanduel odds data------------------
Denver Nuggets (-136) @ Miami Heat (116)
---------------XGBoost Model Predictions---------------
Miami Heat vs Denver Nuggets (55.0%): OVER 215 (70.6%)
------------Expected Value & Kelly Criterion-----------
Miami Heat EV: -2.71 Fraction of Bankroll: 0%
Denver Nuggets EV: -4.63 Fraction of Bankroll: 0%
-------------------------------------------------------
```

**2**
`python3 main.py -xgb -kc`
```
Denver Nuggets vs Miami Heat: 215
Denver Nuggets odds: -136
Miami Heat odds: 116
---------------XGBoost Model Predictions---------------
Denver Nuggets (69.8%) vs Miami Heat: UNDER 215 (56.1%)
------------Expected Value & Kelly Criterion-----------
Denver Nuggets EV: 21.09 Fraction of Bankroll: 28.94%
Miami Heat EV: -34.72 Fraction of Bankroll: 0%
-------------------------------------------------------
```

**Comment by jlucas03** [comment]
Correct me if wrong, I havent looked at this code in a long time but I used it a bit last season.  But `-odds=parameter` is what tells the code which odds you would like to see.  

So for example in the first one you are seeing the odds that fanduels has because of `-odds=fanduels`

but the 2nd one doesnt have one set so it uses the default which could be like `-odds=draftkings` or another betting platform.

hope this helps

**Comment by cpjolicoeur** [comment]
@jlucas03 yeah that isnt fully correct.  When you dont provide the `-odds` prompt, the app script prompts you to manually enter the odds data (it doesnt pull the odds from a "default" sportsbook).

The OP is asking why the model gives different results if he enters the same manual odds values that the `-odds=fanduel` is fetching.

**Comment by cpjolicoeur** [comment]
@AllInOneYT I'm not personally seeing that same effect you are.  I get the same output when running the same model against manually inputted odds or using the `-odds` parameter.

Are you still seeing this issue when running the latest code and models?
