### ISSUE TITLE
python version, EV result explanation, recommended platform to get odds input and over/under

### ISSUE THREAD

**Issue by mghattas100** [kyleskom/NBA-Machine-Learning-Sports-Betting#26]
First of all, great work done. I appreciate your time and efforts put into this. I have a few questions for you:
1) What python version is the most optimal for the required packages to be installed properly? 

2) Can you elaborate more with examples on what EV is used for and how to interpret the results? I see the first part of the result is the percent chance of winning while the second part is the expected value where it says a number next to each team. I also saw you said the best prediction is to use a positive EV for the pick but what if the team that has positive EV isn't necessarily the predicted team to win in the first part of the result? Can you tell me how EV is calculated as well?

3) Where is the odds stats provided from in this code? and do you recommend a specific platform to know what the odds and the over/under of the game in interest?

**Comment by kyleskom** [comment]
1.) I am using 3.9 but I believe 3.8 is also ok.
2.) EV is used to account for payouts as well and win percentage. If a team has a very small chance of winning but the payout is enormous, it might be worth to take that. I would definitely look more into expected value when betting. That should explain more more clearly. 
3.) Where you get your odds from for current games will not matter. The output will account for changes in odds.
