### ISSUE TITLE
No games found

### ISSUE THREAD

**Issue by JP23000** [kyleskom/NBA-Machine-Learning-Sports-Betting#264]
Why am I getting an error for no games found when I run the python3 main.py -xgb -odds=draftkings  during the summer league?

**Comment by mike-bostedt** [comment]
This does not support summer league game and I don't think a summer league model would be any good. Not enough games to train on, not enough consistency in players.

**Comment by kyleskom** [comment]
Exactly that.

**Comment by JP23000** [comment]
But how is a degenerate like me supposed to scratch that itch on the worst week of sports gambling, MLB All Star Break, if I cant bet on Summer League.... And if you tell me WNBA im going to reach out to a gambling hotline so they can help you with your gambling problem.
