### ISSUE TITLE
Support for Mac M1 arm64

### ISSUE THREAD

**Issue by aaronwritescode** [kyleskom/NBA-Machine-Learning-Sports-Betting#274]
Running into different issues trying to set this up as is on my macbook w/ m1 chip. Anyone successfully set this up running main.py like in the example in the README.md w/ M1?

**Comment by omerkymcu** [comment]
I ran it, created a virtual environment for [Python](https://www.google.com/search?q=Python), installed the necessary requirements in it, and ran it there. It is working.
python -m venv nba
source ./nba/bin/activate

**Comment by kyleskom** [comment]
What issues are you running into?

**Comment by aaronwritescode** [comment]
Using python3.8 in venv, first issue on running install requirements command was: 
`ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.0 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0)
ERROR: No matching distribution found for tensorflow==2.11.0`

1. Tried moving this below keras==2.11.0 line in requirements.txt b/c saw that in commit history ==> `Collecting requests==2.28.2 (from -r requirements.txt (line 1))
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting tqdm==4.64.1 (from -r requirements.txt (line 2))
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting colorama==0.4.6 (from -r requirements.txt (line 3))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pandas==1.5.3 (from -r requirements.txt (line 4))
  Using cached pandas-1.5.3-cp38-cp38-macosx_11_0_arm64.whl (10.8 MB)
Collecting numpy==1.24.2 (from -r requirements.txt (line 5))
  Using cached numpy-1.24.2-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
Collecting scikit-learn==1.2.1 (from -r requirements.txt (line 6))
  Using cached scikit_learn-1.2.1-cp38-cp38-macosx_12_0_arm64.whl (8.3 MB)
Collecting keras==2.11.0 (from -r requirements.txt (line 7))
  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)`
`ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 2.14.0rc0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.0 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0)`
`ERROR: No matching distribution found for tensorflow==2.11.0`
2. Changed to python3.9 ==> got rid of 3.9 error message but same result w/ tensorflow=2.11.0 error
3. Changed to tensorflow==2.13.0. Result: 
`ERROR:Cannot install keras==2.11.0 and tensorflow because these package versions have conflicting dependencies.`
`The conflict is caused by:`
`The user requested keras==2.11.0`
`tensorflow-macos 2.13.0 depends on keras<2.14 and >=2.13.1`
4. Changed to keras==2.13.1. Result: SUCCESS 

Now running into same issue as https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/248 when trying to run main.py
