### ISSUE TITLE
segmentation fault python3 main.py -xgb

### ISSUE THREAD

**Issue by CapperDonKarimno** [kyleskom/NBA-Machine-Learning-Sports-Betting#28]
after four grueling months to finally get Tensorflow and all the dependencies installed ... this is the result of running the program for 6 days.....?????????????? ready to give up and move on. it seems impossible to use other people's python programs....! Worst language ever in this regard .!!!!
anyway here is the error message...?

FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stats = home_team_series.append(away_team_series)
Chicago Bulls vs Minnesota Timberwolves: 241.5
Chicago Bulls odds: -3.5
Minnesota Timberwolves odds: 3.5
/Users/adamarie/Desktop/NBA-Machine-Learning-Sports-Betting-master/main.py:35: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stats = home_team_series.append(away_team_series)
Utah Jazz vs Orlando Magic: 222.5
Utah Jazz odds: -13.5
Orlando Magic odds: 13.5
/Users/adamarie/Desktop/NBA-Machine-Learning-Sports-Betting-master/main.py:35: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stats = home_team_series.append(away_team_series)
---------------XGBoost Model Predictions---------------
zsh: segmentation fault  python3 main.py -xgb

crash, crash, and crash!!

**Comment by judirin** [comment]
@CapperDonKarimno hello,

You need to write the american odds for each team to win. You're writing the Handicaps

**Comment by kyleskom** [comment]
Exactly as @judirin has mentioned. You can take a look at the input from the image on the home page. This should help clear up the confusion.

**Comment by Emillzz45** [comment]
<img width="397" alt="Screen Shot 2022-03-12 at 12 11 01 AM" src="https://user-images.githubusercontent.com/68090693/158004763-2227d13a-6675-440e-a6f5-6ad55819ebd8.png">


Recently switched from PC where I had no issues to Mac and started receiving the same error. (intel based)
