### ISSUE TITLE
Traceback (most recent call last):   File "/content/main.py", line 4, in <module>     from colorama import Fore, Style ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by Gxent** [kyleskom/NBA-Machine-Learning-Sports-Betting#287]
Traceback (most recent call last):
  File "/content/main.py", line 4, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'

**Comment by kyleskom** [comment]
Run `pip3 install colorama`
