### ISSUE TITLE
2023-24 Days Rest

### ISSUE THREAD

**Issue by kyleskom** [kyleskom/NBA-Machine-Learning-Sports-Betting#288]
HI @nkgilley I believe the file Data/nba-2022-UTC.csv is used to calculate days rest, can you explain how to generate this file for the upcoming season. Thank you!

**Comment by nkgilley** [comment]
I remember finding this pretty quickly last year with a google search.  Let me see if I can find it again.

**Comment by nkgilley** [comment]
https://fixturedownload.com/download/csv/nba-2023

https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/pull/289

**Comment by kyleskom** [comment]
You are amazing, thanks for your help again.
