### ISSUE TITLE
Python Crashes and throws Segmentation Fault Error for -xgb Model

### ISSUE THREAD

**Issue by jhademcconnell** [kyleskom/NBA-Machine-Learning-Sports-Betting#29]
After installing the packages and running main.py, Python crashes and the terminal outputs a "segmentation fault" error when using the -xgb model: 
<img width="818" alt="image" src="https://user-images.githubusercontent.com/13276370/159617028-62776c60-083a-4119-b206-3a9df563f9b1.png">

Using the -nn model does not throw this error. Has anyone else ran into this issue? If so, what did you do in order to get around it?

Here's some additional debugging output:

---------------XGBoost Model Predictions---------------
Fatal Python error: Segmentation fault

Thread 0x000000010319de00 (most recent call first):
  File "/Library/Frameworks/Python.framework/Version
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by kyleskom** [comment]
Haven't see this one before. I will keep an eye out. If you try for a different day say today does it still throw this error?

**Comment by amritjohar20** [comment]
Also got this issue, tried today's games and got the error.

**Comment by prashundey** [comment]
+1 the same issue still occurs. Running on MacOS

**Comment by prashundey** [comment]
Fixed by specifying xgboost==1.6.2 in requirements.
