### ISSUE TITLE
why are the forecasts so different than the year before?

### ISSUE THREAD

**Issue by Gxent** [kyleskom/NBA-Machine-Learning-Sports-Betting#296]

**Comment by kyleskom** [comment]
Can you elaborate more?

**Comment by Gxent** [comment]
Last year the predictions were almost always right when it came to whether (over or under)

**Comment by kyleskom** [comment]
It's preseason

**Comment by Gxent** [comment]
yes, but don't the values ​​also support this or does that falsify the values?

**Comment by kyleskom** [comment]
It's grabs team stats over the season. Starters don't play ect. I like to give it a few weeks into the regular season for teams stats to develop

**Comment by Gxent** [comment]
Ah ok thx Bro. 👍🏻
