### ISSUE TITLE
Introduction of ```src.Utils.tools``` appears to be creating errors when getting new data

### ISSUE THREAD

**Issue by ethan-hurst** [kyleskom/NBA-Machine-Learning-Sports-Betting#297]
I went through the commit history and diffs and this was added on line 10 of Get_Data.py. 

I'm now consistently getting errors across operating systems. 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ethan/NBA-Machine-Learning-Sports-Betting/src/Process-Data/Get_Data.py", line 10, in <module>
    from src.Utils.tools import get_json_data, to_data_frame
ModuleNotFoundError: No module named 'src'
```

Can we move these functions into the Get_Data.py file? Or can we fix the pathing?

**Comment by kyleskom** [comment]
Ya this is bit of a weird one I found. If I run locally this is not required but is required for my setup on pycharm for some reason. Just remove `src`
