### ISSUE TITLE
Possible issue with get_data.py

### ISSUE THREAD

**Issue by supersheepbear** [kyleskom/NBA-Machine-Learning-Sports-Betting#30]
I am testing:
* using main.py to request  today's team data from stats.nba.com (today's date is 04/03/2022)
* using get_data.py to request team data from today's exactly date. i.e 04/03/2022

In theory these two data sets should be exactly matched, but I see that the excel file created by get_data.py seems not correct.
attached is the excel file I created for  04/03/2022, using get_data.py.
[4-3-2021-22.xlsx](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/files/8404979/4-3-2021-22.xlsx)

The win lost numbers are different from the actual current league stats.
I doubt if this is some issue from my running procedure, or the request url. I can't tell at this moment.

Another suggestion is that nba_api is a very good package to download the nba team stats, which can be considered.

**Comment by kyleskom** [comment]
From a quick look just now this does seem pretty off. Ill take a deeper look at this today.

**Comment by kyleskom** [comment]
I just checked and the data that is used for the predictions is still accurate so there should be no issues with game predictions. I suspect with some testing of get_data earlier this year I didn't change the format back correctly. Will take a look at that and push a fix.

**Comment by kyleskom** [comment]
`DateFrom=10%2F29%2F{2}` While running for an earlier season this is the code set. This season started earlier than this date. This seasons data was not included in the model hence I did not need to update and run for this season.

 If you need this data you can always update that yourself, but as I don't include current season for training, closing this issue for now. Will be updated for next season in my models.
