### ISSUE TITLE
kyleskom have you had much success betting?

### ISSUE THREAD

**Issue by Gxent** [kyleskom/NBA-Machine-Learning-Sports-Betting#302]
Do you perhaps have a few tips on how best to bet?

**Comment by sportsfan69** [comment]
I did it about later half of the season last season. I did choose ML most of the time. There are times when it gives underdog the higher percentage for winning, in those instances I found the safer option was to do the point spread as you are covered if they cover the spread or win. However, more money would be won with a ML on the underdog. There were days the model would have only have one loser and there were days we went like 2 and 6. If the odds for the favorite are really bad like -200 or worse I would try to mix it with another one to make a small parlay. 

The over/unders has a lower success rate so, i've always tried to stay away from it.

**Comment by Gxent** [comment]
However, I have made more profits with over/under than if I bet on the winner

**Comment by Baaios** [comment]
Hello Gxent, you said in a previous discussion, i think, that you got 2k from 10$ bet per game on OU. How did you manage that? With parlays? From the time i read your comment I haven't manage to get it out of my mind. Thank you

**Comment by Gxent** [comment]
I just always took over and under bets because that was the most likely thing to happen.

**Comment by Baaios** [comment]
But the accuracy is 55%. It's not possible to reach 2000 with 10$ per game right? Do you remember how long it took you to reach that amount? Thank you for replying!

**Comment by Gxent** [comment]
No, I made $110 out of $10 and then always doubled it. The second game didn't happen because I didn't have a team, otherwise I would have made $1200 on the third day.

write to me on Discord Gent#7049

**Comment by thprtm** [comment]
> No, I made $110 out of $10 and then always doubled it. The second game didn't happen because I didn't have a team, otherwise I would have made $1200 on the third day.
> 
> write to me on Discord Gent#7049

Added on Discord. Interested in what you betted on (Colab or downloaded version? Seems it gives different results)
