### ISSUE TITLE
Error when running python3 main.py -xgb -odds=fanduel

### ISSUE THREAD

**Issue by dexinthecity** [kyleskom/NBA-Machine-Learning-Sports-Betting#309]
What am I doing wrong?

![Screenshot 2023-10-23 010229](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/34484238/03674a78-8709-4849-a7a8-e42dab4854cd)

**Comment by tunetyme** [comment]
I beleive it is the version of Python.

**Comment by kyleskom** [comment]
What version on python are you using?

**Comment by dexinthecity** [comment]
> What version on python are you using?

I ended up getting it to work with the help of chatgpt LOL 

I'm able to generate recommendations now. There is however this warning that pops up

"main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)"

**Comment by kyleskom** [comment]
Thats fine, just a warning.

**Comment by tgbgb** [comment]
> _

what was the fix. Getting the same issue

**Comment by tgbgb** [comment]
NM. requires python 3.11.

**Comment by ethan-hurst** [comment]
Isn't this tensor flow for apple metal? 
If you're on windows. Drop it from the requirements
