### ISSUE TITLE
using colab, gave wrong data on who is playing who

### ISSUE THREAD

**Issue by byno1022** [kyleskom/NBA-Machine-Learning-Sports-Betting#316]
gave me:The model predicts that the Milwaukee Bucks will beat the Toronto Raptors, the Brooklyn Nets will beat the San Antonio Spurs, the Denver Nuggets will beat the Portland Trail Blazers, and the LA Clippers will beat the Philadelphia 76ers. All four predicted winners are expected to score less than their point totals from the previous game.

**Comment by kyleskom** [comment]
No idea what this even means.
