### ISSUE TITLE
OVER None

### ISSUE THREAD

**Issue by elfrost** [kyleskom/NBA-Machine-Learning-Sports-Betting#322]
Hello, is it normal its all over at none?
Charlotte Hornets (65.8%) vs Detroit Pistons: OVER None (70.8%)
Memphis Grizzlies vs Denver Nuggets (62.0%): OVER None (92.0%)
Atlanta Hawks (57.0%) vs New York Knicks: OVER None (62.9%)
Boston Celtics (65.2%) vs Miami Heat: OVER None (54.6%)
Cleveland Cavaliers vs Oklahoma City Thunder (53.1%): OVER None (61.7%)
Chicago Bulls vs Toronto Raptors (56.8%): OVER None (91.8%)
San Antonio Spurs (65.7%) vs Houston Rockets: OVER None (76.3%)
Dallas Mavericks (71.6%) vs Brooklyn Nets: OVER None (73.6%)
Utah Jazz vs LA Clippers (64.7%): OVER None (62.3%)
Portland Trail Blazers vs Orlando Magic (67.0%): OVER None (79.9%)
Sacramento Kings (73.5%) vs Golden State Warriors: OVER None (74.8%)

**Comment by sact1909** [comment]
same here

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/23615129/a106e03b-620f-4e61-a998-d93968f5b80e)

**Comment by Skysafe64** [comment]
> Hello, is it normal its all over at none? Charlotte Hornets (65.8%) vs Detroit Pistons: OVER None (70.8%) Memphis Grizzlies vs Denver Nuggets (62.0%): OVER None (92.0%) Atlanta Hawks (57.0%) vs New York Knicks: OVER None (62.9%) Boston Celtics (65.2%) vs Miami Heat: OVER None (54.6%) Cleveland Cavaliers vs Oklahoma City Thunder (53.1%): OVER None (61.7%) Chicago Bulls vs Toronto Raptors (56.8%): OVER None (91.8%) San Antonio Spurs (65.7%) vs Houston Rockets: OVER None (76.3%) Dallas Mavericks (71.6%) vs Brooklyn Nets: OVER None (73.6%) Utah Jazz vs LA Clippers (64.7%): OVER None (62.3%) Portland Trail Blazers vs Orlando Magic (67.0%): OVER None (79.9%) Sacramento Kings (73.5%) vs Golden State Warriors: OVER None (74.8%)



> same here
> 
> ![image](https://user-images.githubusercontent.com/23615129/278804354-a106e03b-620f-4e61-a998-d93968f5b80e.png)

Hi there! It seems like the issue you're encountering is due to running the program too early in the day. At that time, some of the odds for the matches might not have been released yet. That's why you're seeing 'None' for some of the matchups. I'd recommend waiting a bit later in the day or closer to the game time to get the complete odds. Hope this helps!
