### ISSUE TITLE
Tensorflow Metal Install Error

### ISSUE THREAD

**Issue by sact1909** [kyleskom/NBA-Machine-Learning-Sports-Betting#323]
When it's running the command to install the requirements libs, I'm getting the following error 

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/23615129/c476b54a-8ced-42c9-898d-bb38f2e58e3c)

In my machine
PC (Windows)
Python 3.11.5

Using Docker
Python version 3.11.5

**Comment by kyleskom** [comment]
Are you using windows? Might not need that as its Mac only

**Comment by sact1909** [comment]
@kyleskom thanks, it's true, I tested it on my mac and it worked as expected...
