### ISSUE TITLE
"no module named src"

### ISSUE THREAD

**Issue by Noehy** [kyleskom/NBA-Machine-Learning-Sports-Betting#324]
I have all of the required dependencies installed, and every time I try to get new data this happens.

`C:\>cd NBA-Machine-Learning-Sports-Betting

C:\NBA-Machine-Learning-Sports-Betting>cd src/Process-Data

C:\NBA-Machine-Learning-Sports-Betting\src\Process-Data>python -m Get_Data
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\NBA-Machine-Learning-Sports-Betting\src\Process-Data\Get_Data.py", line 10, in <module>
    from src.Utils.tools import get_json_data, to_data_frame
ModuleNotFoundError: No module named 'src'`

**Comment by sact1909** [comment]
Just create a folder called src inside this route src/Process-Data and copy the folder Utils from src folder and pasted into the new src folder inside Process-Data

That works for me for now meanwhile the fix it

**Comment by Noehy** [comment]
Thank you!

**Comment by cpjolicoeur** [comment]
can also just symlink it instead of copying

```bash
cd src/Process-Data
ln -nfs ../. src
```
