### ISSUE TITLE
Flask error went open the page

### ISSUE THREAD

**Issue by sact1909** [kyleskom/NBA-Machine-Learning-Sports-Betting#325]
I'm trying to run the Flask web portal, but I'm getting this error

<img width="979" alt="image" src="https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/23615129/a64063c7-51d6-4818-9ebb-e5b834e095e9">

<img width="801" alt="image" src="https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/23615129/c3e43e08-17f4-4bcb-a82d-b1bbb7ffa664">

I'm using on a mac m1 
and I installed Flask and jinja2 in case of that, but the problem continue

**Comment by DillonMercz** [comment]
Seems like you have a PATH error. Its trying to find Python, but python doesn't seem to be defined in path. On Mac you can just brew install python and that should fix the issue.

**Comment by fuzmik** [comment]
manual uninstall flask then pip install flask again
