### ISSUE TITLE
Model output has incorrect mapping of over/under line to game being played for some games

### ISSUE THREAD

**Issue by handleygf** [kyleskom/NBA-Machine-Learning-Sports-Betting#328]
![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/14012687/82c8f4af-097e-4889-843f-b09308f52bd6)

- O/U for Wizards vs Grizzlies on draftkings is 228, output says 214.5
- O/U for Pels vs Knicks on draftkings is 223.5, output says 228
- O/U for Pistons vs Bulls on draftkings is 214.5, output says 223.5

The rest are correct. DK lines are according to the DK app as of 10/28 2pm PST. Model was ran at the same time as well on Google Colab

**Comment by handleygf** [comment]
It looks like the ML odds are incorrect too, not just Over Under. It looks like the following is happening:

- Grizzlies/Wizards it taking the odds data for Bulls/Pistons
- Knicks/Pels is taking the odds data for Grizzlies/Wizards
- Bulls/Pistons is taking the odds data for Knicks/Pels

DK app as of 10/28 2pm PST:
     - Chicago Bulls (-142) vs Detroit Pistons (120), O/U 214.5
     - Memphis Grizzlies (-112) vs Washington Wizards (-108) O/U 228
     - NY Knicks (124) vs NO Pelicans (-148) O/U 223.5

**Comment by kyleskom** [comment]
Will take a look into this

**Comment by handleygf** [comment]
Fwiw not currently seeing the issue for the next set of games for 10/29

**Comment by stvAdams** [comment]
I'm continuing to see this issue.  Seems fine yesterday, 11/6 it's returning wildly different data if run consecutively when I run:
"python3 main.py -xgb -odds=draftkings -kc" a few times in a row.   Actually seems ok yesterday, so not sure what's different day-to-day?

**Comment by acmeGR** [comment]
Same issue here. Strange thing is that when I try it through colab, I get the correct lines. The issue happens with local output.

**Comment by magic8bull** [comment]
![Screenshot 2023-11-06 at 1 17 51 PM](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/150061083/a0915774-3650-4c29-afc1-721faa5526b3)
![Screenshot 2023-11-06 at 1 18 05 PM](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/150061083/7ea6a39f-90d4-4bd0-9ddd-860c6a4cf30c)

couple of examples attached above of data run moments apart with the same command.

**Comment by magic8bull** [comment]
I "think" the issue here is related to the Dictionaries.py --> team_index_current referring to the "Philadelphia 76ers" vs. the "Philadelphia Sixers".   The may cause odds to be misaligned on days that the Sixers play, but fine on days they don't?

**Comment by kyleskom** [comment]
Will take a deeper look into this

**Comment by magic8bull** [comment]
I apologize, I don't think that "Philadelphia Sixers" is the issue.  I was sloppy and asked ChatGPT to compare the dictionary to the sportsbookreview.com schema, and it came back and said the "76ers" didn't match the "Sixers".  I assumed sportsbookreview.com updated the schema this season and threw things off.  It appears ChatGPT is dumb, sportsbookreview.com is still a value of "76ers".  That said, I'm still having the issue above, but my comment above was unintentionally a red herring to what is actually causing the mapping issue.

**Comment by kyleskom** [comment]
Fixed
