### ISSUE TITLE
getting today's games

### ISSUE THREAD

**Issue by Ahmed4221** [kyleskom/NBA-Machine-Learning-Sports-Betting#33]
Hey
Can you share some documentation link for this api?
"'https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2021/scores/00_todays_scores.json"
I am trying to test the api on a given date, this gives empty response because there were no matches today but I need the docs so I can put in a date and test my pipeline

**Comment by kyleskom** [comment]
There is no doc for this. This is custom wrote to pull data from here [https://www.nba.com/games](https://www.nba.com/games)
