### ISSUE TITLE
Issue w/Clone Install

### ISSUE THREAD

**Issue by gstuart13** [kyleskom/NBA-Machine-Learning-Sports-Betting#330]
Cloning into 'NBA-Machine-Learning-Sports-Betting'...
remote: Enumerating objects: 18653, done.
remote: Counting objects: 100% (257/257), done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 18653 (delta 121), reused 189 (delta 81), pack-reused 18396
Receiving objects: 100% (18653/18653), 395.74 MiB | 28.08 MiB/s, done.
Resolving deltas: 100% (7221/7221), done.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
python3: can't open file '/content/main.py': [Errno 2] No such file or directory

Trying to install with google colab and visual code. Same error.

**Comment by Baaios** [comment]
Hello, copy and paste the following:

#Remove Preexisting Files
! rm -rf NBA-Machine-Learning-Sports-Betting
! rm -rf *

#Bootstrap Files
! git clone https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting.git
! mv -v ./NBA-Machine-Learning-Sports-Betting/* .
! pip3 install colorama
! pip3 install pandas==2.1.0
! pip3 install sbrscrape
! pip3 install tensorflow==2.11.0
! pip3 install tensorflow-meta
! pip3 install xgboost
! pip3 install tqdm
! pip3 install flask
! pip3 install scikit-learn

#Clear Bootstrap Logs
from IPython.display import clear_output
clear_output()

print("Successful Bootstrap!!!")

**Comment by gstuart13** [comment]
That worked and now everything is running in order. THank you!
