### ISSUE TITLE
Google Colab issue - No XGBoost Model Predictions or Expected Value Output. 

### ISSUE THREAD

**Issue by mthunt675** [kyleskom/NBA-Machine-Learning-Sports-Betting#331]
I ran this at 8:00 am EST on 10/29 with no issues on output. Ran it again at 1:33 pm EST and got the below. 

! python3 main.py -xgb -odds=fanduel

output
2023-10-29 17:33:23.178029: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-29 17:33:24.910024: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-10-29 17:33:24.910160: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-10-29 17:33:24.910180: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-10-29 17:33:28.159389: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
------------------fanduel odds data------------------
Denver Nuggets (-166) @ Oklahoma City Thunder (140)
Golden State Warriors (-215) @ Houston Rockets (180)
Atlanta Hawks (198) @ Milwaukee Bucks (-240)
Portland Trail Blazers (360) @ Philadelphia 76ers (-460)
San Antonio Spurs (118) @ LA Clippers (-138)
Los Angeles Lakers (330) @ Sacramento Kings (-420)
Traceback (most recent call last):
  File "/content/main.py", line 139, in <module>
    main()
  File "/content/main.py", line 111, in main
    data, todays_games_uo, frame_ml, home_team_odds, away_team_odds = createTodaysGames(games, df, odds)
  File "/content/main.py", line 52, in createTodaysGames
    schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_format='%d/%m/%Y %H:%M')
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
TypeError: read_csv() got an unexpected keyword argument 'date_format'

**Comment by nkgilley** [comment]
Try updating `pandas`

**Comment by byno1022** [comment]
having the same issues, updating pandas does not help.

**Comment by Baaios** [comment]
Hello everything is alright, try !pip3 install pandas==2.1.0

**Comment by pedrocastellanos** [comment]
> !pip3 install pandas==2.1.0

It works

**Comment by thprtm** [comment]
Google Colad or cloning (downloading) the zip is more updated? also i got different values (Los Angeles Lakers (69.6%) vs Orlando Magic: UNDER 218.5 (79.9%) in downloaded ZIP on my PC and Los Angeles Lakers vs Orlando Magic (64.8%): OVER 218.5 (58.2%) when run on Colab. I am confused...

**Comment by VNWind88** [comment]
I am encountering src issue when I tried to run mine. Any help would be really appreciated
Traceback (most recent call last):
  File "c:\Users\Owner\Documents\GitHub\NBA-Machine-Learning-Sports-Betting\main.py", line 9, in <module>
    from src.Predict import NN_Runner, XGBoost_Runner
  File "c:\Users\Owner\Documents\GitHub\NBA-Machine-Learning-Sports-Betting\src\Predict\NN_Runner.py", line 12, in <module>
    model = load_model('Models/NN_Models/Trained-Model-ML-1680133120.689445')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Roaming\Python\Python311\site-packages\keras\src\saving\saving_api.py", line 262, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Roaming\Python\Python311\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Owner\AppData\Roaming\Python\Python311\site-packages\keras\src\saving\legacy\saved_model\load.py", line 113, in load
    raise IOError(
OSError: Cannot parse keras metadata at path Models/NN_Models/Trained-Model-ML-1680133120.689445\keras_metadata.pb: Received error: Error parsing message

**Comment by Tonigno** [comment]
> Google Colad or cloning (downloading) the zip is more updated? also i got different values (Los Angeles Lakers (69.6%) vs Orlando Magic: UNDER 218.5 (79.9%) in downloaded ZIP on my PC and Los Angeles Lakers vs Orlando Magic (64.8%): OVER 218.5 (58.2%) when run on Colab. I am confused...

Hi, I have different values for that match (run in colab). Here is the full output: 

------------------fanduel odds data------------------
Brooklyn Nets (-122) @ Charlotte Hornets (104)
Boston Celtics (128) @ Washington Wizards (-152)
Chicago Bulls (-490) @ Indiana Pacers (380)
Portland Trail Blazers (-124) @ Toronto Raptors (106)
Minnesota Timberwolves (250) @ Atlanta Hawks (-310)
Golden State Warriors (134) @ New Orleans Pelicans (-158)
Miami Heat (172) @ Milwaukee Bucks (-205)
Detroit Pistons (184) @ Oklahoma City Thunder (-220)
Dallas Mavericks (-142) @ Memphis Grizzlies (120)
Utah Jazz (265) @ Denver Nuggets (-330)
Orlando Magic (122) @ Los Angeles Lakers (-144)
---------------XGBoost Model Predictions---------------
Charlotte Hornets (59.9%) vs Brooklyn Nets: OVER 228.5 (73.8%)
Washington Wizards (51.1%) vs Boston Celtics: UNDER 226.5 (59.6%)
Indiana Pacers (67.1%) vs Chicago Bulls: OVER 229.5 (51.3%)
Toronto Raptors (73.0%) vs Portland Trail Blazers: OVER 234.5 (58.9%)
Atlanta Hawks vs Minnesota Timberwolves (50.3%): UNDER 217.5 (56.1%)
New Orleans Pelicans (71.1%) vs Golden State Warriors: UNDER 232.5 (55.6%)
Milwaukee Bucks (65.3%) vs Miami Heat: UNDER 223.5 (69.3%)
Oklahoma City Thunder (50.7%) vs Detroit Pistons: UNDER 226.5 (80.3%)
Memphis Grizzlies vs Dallas Mavericks (50.3%): UNDER 227.5 (65.7%)
Denver Nuggets (71.6%) vs Utah Jazz: UNDER 230.5 (63.8%)
Los Angeles Lakers vs Orlando Magic (64.8%): OVER 220.5 (58.2%)
------------Expected Value & Kelly Criterion-----------
Charlotte Hornets EV: 22.13 Fraction of Bankroll: 21.28%
Brooklyn Nets EV: -26.97 Fraction of Bankroll: 0%
Washington Wizards EV: -15.35 Fraction of Bankroll: 0%
Boston Celtics EV: 11.59 Fraction of Bankroll: 9.05%
Indiana Pacers EV: 222.3 Fraction of Bankroll: 58.5%
Chicago Bulls EV: -60.44 Fraction of Bankroll: 0%
Toronto Raptors EV: 50.43 Fraction of Bankroll: 47.57%
Portland Trail Blazers EV: -51.27 Fraction of Bankroll: 0%
Atlanta Hawks EV: -34.26 Fraction of Bankroll: 0%
Minnesota Timberwolves EV: 76.02 Fraction of Bankroll: 30.41%
New Orleans Pelicans EV: 16.04 Fraction of Bankroll: 25.13%
Golden State Warriors EV: -32.28 Fraction of Bankroll: 0%
Milwaukee Bucks EV: -2.8 Fraction of Bankroll: 0%
Miami Heat EV: -5.71 Fraction of Bankroll: 0%
Oklahoma City Thunder EV: -26.26 Fraction of Bankroll: 0%
Detroit Pistons EV: 40.01 Fraction of Bankroll: 21.75%
Memphis Grizzlies EV: 9.39 Fraction of Bankroll: 7.83%
Dallas Mavericks EV: -14.32 Fraction of Bankroll: 0%
Denver Nuggets EV: -6.74 Fraction of Bankroll: 0%
Utah Jazz EV: 3.76 Fraction of Bankroll: 1.42%
Los Angeles Lakers EV: -40.41 Fraction of Bankroll: 0%
Orlando Magic EV: 43.93 Fraction of Bankroll: 36.01%
-------------------------------------------------------
------------Neural Network Model Predictions-----------
Charlotte Hornets (59.6%) vs Brooklyn Nets: UNDER 228.5 (50.2%)
Washington Wizards vs Boston Celtics (63.4%): UNDER 226.5 (52.8%)
Indiana Pacers (79.0%) vs Chicago Bulls: UNDER 229.5 (50.9%)
Toronto Raptors (72.9%) vs Portland Trail Blazers: UNDER 234.5 (51.0%)
Atlanta Hawks (56.7%) vs Minnesota Timberwolves: UNDER 217.5 (51.3%)
New Orleans Pelicans (60.5%) vs Golden State Warriors: UNDER 232.5 (50.1%)
Milwaukee Bucks (63.7%) vs Miami Heat: UNDER 223.5 (53.0%)
Oklahoma City Thunder (52.7%) vs Detroit Pistons: UNDER 226.5 (50.6%)
Memphis Grizzlies vs Dallas Mavericks (67.4%): UNDER 227.5 (54.1%)
Denver Nuggets (80.1%) vs Utah Jazz: UNDER 230.5 (52.3%)
Los Angeles Lakers vs Orlando Magic (63.6%): UNDER 220.5 (53.3%)
------------Expected Value & Kelly Criterion-----------
Charlotte Hornets EV: 21.51 Fraction of Bankroll: 20.69%
Brooklyn Nets EV: -26.42 Fraction of Bankroll: 0%
Washington Wizards EV: -39.3 Fraction of Bankroll: 0%
Boston Celtics EV: 44.52 Fraction of Bankroll: 34.78%
Indiana Pacers EV: 279.05 Fraction of Bankroll: 73.43%
Chicago Bulls EV: -74.68 Fraction of Bankroll: 0%
Toronto Raptors EV: 50.14 Fraction of Bankroll: 47.3%
Portland Trail Blazers EV: -51.01 Fraction of Bankroll: 0%
Atlanta Hawks EV: -25.05 Fraction of Bankroll: 0%
Minnesota Timberwolves EV: 51.65 Fraction of Bankroll: 20.66%
New Orleans Pelicans EV: -1.26 Fraction of Bankroll: 0%
Golden State Warriors EV: -7.5 Fraction of Bankroll: 0%
Milwaukee Bucks EV: -5.27 Fraction of Bankroll: 0%
Miami Heat EV: -1.19 Fraction of Bankroll: 0%
Oklahoma City Thunder EV: -23.28 Fraction of Bankroll: 0%
Detroit Pistons EV: 34.2 Fraction of Bankroll: 18.59%
Memphis Grizzlies EV: -28.38 Fraction of Bankroll: 0%
Dallas Mavericks EV: 14.94 Fraction of Bankroll: 20.94%
Denver Nuggets EV: 4.37 Fraction of Bankroll: 13.77%
Utah Jazz EV: -27.36 Fraction of Bankroll: 0%
Los Angeles Lakers EV: -38.33 Fraction of Bankroll: 0%
Orlando Magic EV: 41.2 Fraction of Bankroll: 33.77%
-------------------------------------------------------

I'm confused too if I look at your outputs.

**Comment by thprtm** [comment]
Today's ouput (XGBoost):
Philadelphia 76ers (78.9%) vs Toronto Raptors: UNDER 215 (53.4%)
New Orleans Pelicans (64.5%) vs Detroit Pistons: OVER 217.5 (54.2%)
Utah Jazz vs Orlando Magic (59.5%): UNDER 222 (70.7%)
Phoenix Suns (68.5%) vs San Antonio Spurs: UNDER 225.5 (50.3%)

**Comment by Tonigno** [comment]
> Today's ouput (XGBoost): Philadelphia 76ers (78.9%) vs Toronto Raptors: UNDER 215 (53.4%) New Orleans Pelicans (64.5%) vs Detroit Pistons: OVER 217.5 (54.2%) Utah Jazz vs Orlando Magic (59.5%): UNDER 222 (70.7%) Phoenix Suns (68.5%) vs San Antonio Spurs: UNDER 225.5 (50.3%)

Mine was these:

```
------------------fanduel odds data------------------
Toronto Raptors (295) @ Philadelphia 76ers (-370)
Detroit Pistons (245) @ New Orleans Pelicans (-300)
Orlando Magic (-104) @ Utah Jazz (-112)
San Antonio Spurs (250) @ Phoenix Suns (-310)
---------------XGBoost Model Predictions---------------
Philadelphia 76ers (78.9%) vs Toronto Raptors: UNDER 216.5 (49.9%)
New Orleans Pelicans (64.5%) vs Detroit Pistons: OVER 219 (53.8%)
Utah Jazz vs Orlando Magic (59.5%): UNDER 222 (70.7%)
Phoenix Suns (68.5%) vs San Antonio Spurs: UNDER 225.5 (50.3%)
------------Expected Value & Kelly Criterion-----------
Philadelphia 76ers EV: 0.24 Fraction of Bankroll: 0.81%
Toronto Raptors EV: -16.7 Fraction of Bankroll: 0%
New Orleans Pelicans EV: -14.02 Fraction of Bankroll: 0%
Detroit Pistons EV: 22.53 Fraction of Bankroll: 9.2%
Utah Jazz EV: -23.35 Fraction of Bankroll: 0%
Orlando Magic EV: 16.73 Fraction of Bankroll: 17.33%
Phoenix Suns EV: -9.35 Fraction of Bankroll: 0%
San Antonio Spurs EV: 10.12 Fraction of Bankroll: 4.05%
-------------------------------------------------------
```
