### ISSUE TITLE
fanduel odds data (NONE AND ONLY CODE) 

### ISSUE THREAD

**Issue by Davdan11** [kyleskom/NBA-Machine-Learning-Sports-Betting#345]
Washington Wizards (None) @ Charlotte Hornets (None)
Utah Jazz (None) @ Indiana Pacers (None)
Boston Celtics (None) @ Philadelphia 76ers (None)
San Antonio Spurs (None) @ New York Knicks (None)
LA Clippers (None) @ Brooklyn Nets (None)
Los Angeles Lakers (None) @ Houston Rockets (None)
Miami Heat (None) @ Memphis Grizzlies (None)
Detroit Pistons (None) @ Milwaukee Bucks (None)
New Orleans Pelicans (None) @ Minnesota Timberwolves (None)
Phoenix Suns (None) @ Chicago Bulls (None)
Cleveland Cavaliers (None) @ Oklahoma City Thunder (None)
Toronto Raptors (None) @ Dallas Mavericks (None)
Golden State Warriors (None) @ Denver Nuggets (None)
Portland Trail Blazers (None) @ Sacramento Kings (None)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py:53: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  schedule_df = pd.read_csv('Data/nba-2023-UTC.csv', parse_dates=['Date'], date_parser=dateparse)
---------------XGBoost Model Predictions---------------
Charlotte Hornets (68.1%) vs Washington Wizards: OVER None (77.9%)
Indiana Pacers (70.2%) vs Utah Jazz: OVER None (76.9%)
Philadelphia 76ers (53.5%) vs Boston Celtics: OVER None (85.8%)
New York Knicks (60.2%) vs San Antonio Spurs: OVER None (82.6%)
Brooklyn Nets vs LA Clippers (55.7%): OVER None (91.8%)
Houston Rockets (64.7%) vs Los Angeles Lakers: OVER None (93.7%)
Memphis Grizzlies vs Miami Heat (62.1%): OVER None (88.3%)
Milwaukee Bucks (67.8%) vs Detroit Pistons: OVER None (86.0%)
Minnesota Timberwolves (69.7%) vs New Orleans Pelicans: OVER None (90.0%)
Chicago Bulls vs Phoenix Suns (56.4%): OVER None (92.0%)
Oklahoma City Thunder (69.9%) vs Cleveland Cavaliers: OVER None (95.9%)
Dallas Mavericks (78.5%) vs Toronto Raptors: OVER None (94.5%)
Denver Nuggets (59.0%) vs Golden State Warriors: OVER None (79.5%)
Sacramento Kings (57.9%) vs Portland Trail Blazers: OVER None (58.7%)
---------------------Expected Value--------------------
Traceback (most recent call last):
  File "C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py", line 140, in <module>
    main()
  File "C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\main.py", line 120, in main
    XGBoost_Runner.xgb_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds, args.kc)
  File "C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\src\Predict\XGBoost_Runner.py", line 89, in xgb_runner
    bankroll_fraction_home = bankroll_descriptor + str(kc.calculate_kelly_criterion(home_team_odds[count], ml_predictions_array[count][0][1])) + '%'
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\src\Utils\Kelly_Criterion.py", line 15, in calculate_kelly_criterion
    decimal_odds = american_to_decimal(american_odds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danjo\NBA-Machine-Learning-Sports-Betting\src\Utils\Kelly_Criterion.py", line 5, in american_to_decimal
    if american_odds >= 100:
       ^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by kyleskom** [comment]
Have an open PR that should fix this issiue.
