### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tereenceeec** [kyleskom/NBA-Machine-Learning-Sports-Betting#346]
![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/43162097/7f379a80-5722-48d4-b281-b3175de7d135)

**Comment by kyleskom** [comment]
What version of pandas are you using?

**Comment by tereenceeec** [comment]
can I ask how to install the packages? I just ran the code via google colab

**Comment by adeka299aaa** [comment]
I got the same error and I am using pandas 1.5.3

**Comment by adeka299aaa** [comment]
> can I ask how to install the packages? I just ran the code via google colab

!pip install <package>

**Comment by adeka299aaa** [comment]
Now, i tried with pandas 2.1.2 and it just worked.
