### ISSUE TITLE
wrong lines

### ISSUE THREAD

**Issue by aaaclones** [kyleskom/NBA-Machine-Learning-Sports-Betting#351]
<img width="674" alt="Screenshot 2023-11-10 at 3 22 41 PM" src="https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/104782042/ab779e93-9b2d-4de3-b527-b0a7ee691a45">
The lines are wrong . Not sure if this is for everyone but this was pulled from google colab just a moment ago . I am not sure how this can be accurate you have 6 predictions north of 70% and a few well above 80 % . There needs to be a disclaimer for people not to be mislead about these predictions .

**Comment by kyleskom** [comment]
Or just don't have the expectations of it being perfect. I am looking into the lines issue
