### ISSUE TITLE
Error after the installation

### ISSUE THREAD

**Issue by MarKaliGG** [kyleskom/NBA-Machine-Learning-Sports-Betting#359]
Hey, im new in this repo and i want test it. When i run the comand python main.py -xgb -odds=fanduel i have this error:

I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
An error occurred: HTTPSConnectionPool(host='www.sportsbookreview.com', port=443): Max retries exceeded with url: /betting-odds/nba-basketball/?date=2023-11-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025913B44DF0>, 'Connection to www.sportsbookreview.com timed out. (connect timeout=None)'))
No games found.

If i take off the -odds he ask me to put manually the odds , btw he ask me :

Washington Wizards vs Dallas Mavericks: (What i have to write here? ) Press enter?
Washington Wizards odds: 2.60 from sisal
Dallas Mavericks odds: 1.50 from sisal

Atlanta Hawks vs New York Knicks:  (What i have to write here? ) Press enter?
Atlanta Hawks odds: 1.90
New York Knicks odds: 1.90

can someone help me to understand how to use this powerful script , thank a lot

**Comment by Skysafe64** [comment]
Hi, Are you sure you have correctly installed all the requirements? 
Can you provide us with screenshots if possible?
