### ISSUE TITLE
pip3 install fails

### ISSUE THREAD

**Issue by aleksa-codes** [kyleskom/NBA-Machine-Learning-Sports-Betting#37]
Running `pip3 install -r requirements.txt` gets me this error:

![Capture](https://user-images.githubusercontent.com/64015178/198975213-6ba5bab8-eee5-46fc-b914-e8a5649b6d9e.PNG)

Also, I was wondering is it possible, if I get it working, to build a UI around it using React or something? Thanks.

**Comment by Emillzz45** [comment]
Same :/

**Comment by kyleskom** [comment]
What version of python are you using?

**Comment by aleksa-codes** [comment]
I've tried with `scikit_learn==1.1.2` and `numpy==1.23.4`, still doesn't work. Tried downgrading numpy versions all the way to `numpy==1.22.4` but no luck. Btw I am using Python 3.11.0 currently. If I or someone else manages to find the working versions, I will gladly update them in the requirements. I am fairly new to Python but had similar issues with some Instagram bots etc. that I managed to fix, seems like a common problem 😂

**Comment by kyleskom** [comment]
It might be the python version. I am using `3.9.7` for this.

**Comment by Emillzz45** [comment]
Yeah 3.9.7 is butter for me! Thank you

**Comment by aleksa-codes** [comment]
@kyleskom got it to work on Python 3.9.13, thank you, very nice project!

**Comment by obtim** [comment]
> @kyleskom got it to work on Python 3.9.13, thank you, very nice project!
Specify the versions of the packages that worked for you! Similar problem: I can't solve
