### ISSUE TITLE
How to run script like in screen?

### ISSUE THREAD

**Issue by nichu96** [kyleskom/NBA-Machine-Learning-Sports-Betting#374]
Hello!

How do I run the script to achieve the effect shown in the screenshot?
<img width="505" alt="output" src="https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/20098158/123fe0b0-8d3a-403e-b7e6-07097d0903b8">

**Comment by kyleskom** [comment]
`python3 main.py -xgb -odds=fanduel`
