### ISSUE TITLE
Input 

### ISSUE THREAD

**Issue by doctorerre** [kyleskom/NBA-Machine-Learning-Sports-Betting#38]
I am very noobie to this proyect and i have some basics knowledge about NBA haha ... 
what i am supposed to enter here ? if you can give me an answer for dummy i would aprecciate it xd

![image](https://user-images.githubusercontent.com/79534115/201422524-cb8d2ceb-437d-4f41-b3dd-ec3688ca0cfa.png)

**Comment by Emillzz45** [comment]
Enter in the over under. Then enter in the teams odds -135 and 175 for example.

**Comment by doctorerre** [comment]
thx! will try it!

**Comment by Emillzz45** [comment]
I should be more detailed. Do over under for the matchup(hit enter) then team odd (enter) you'll get it lol

**Comment by doctorerre** [comment]
Like:

Boston Celtics - Nuggets =  Over/Under +227 
Boston Celtic odds = -135
Nuggets = 175

dont know just putting hipothtetic numbers

**Comment by Emillzz45** [comment]
Spot on

**Comment by Emillzz45** [comment]
No +227 tho

**Comment by doctorerre** [comment]
Got it, thx @Emillzz45

**Comment by Emillzz45** [comment]
No problem boss. Best of luck

**Comment by doctorerre** [comment]
![image](https://user-images.githubusercontent.com/79534115/201435889-913adf88-7b21-45b3-893f-e7efc8251d0e.png)

@Emillzz45 this is my last question , can u help me to interpret this output?

**Comment by kyleskom** [comment]
The top part is games predictions. Green team is projected to win and with what percent chance. Bottom part is expected value of a 100 dollar bet. I would look into what expected value is before moving forward.
