### ISSUE TITLE
Soccer matches 

### ISSUE THREAD

**Issue by GrizzyGamer** [kyleskom/NBA-Machine-Learning-Sports-Betting#389]
I was searching a solution to apply this for soccer betting, can you make a soccer version ?

**Comment by Tonigno** [comment]
That would be great!

**Comment by juanantoniocruzmoreno** [comment]
Sigue funcionando

**Comment by juanantoniocruzmoreno** [comment]
No se como instalar bot en iphone

**Comment by kyleskom** [comment]
Would require an entire re-write. Maybe one day.
