### ISSUE TITLE
Requirements outdated

### ISSUE THREAD

**Issue by michalis97500** [kyleskom/NBA-Machine-Learning-Sports-Betting#39]
Tensorflow v 2.6.0 cannot be installed via pip or pip3, its not in the available versions

**Comment by Emillzz45** [comment]
Which python version you using?

**Comment by michalis97500** [comment]
3.8.15
![image](https://user-images.githubusercontent.com/62388610/202330578-65255649-2618-4f87-94db-464157f6e9e5.png)

**Comment by Emillzz45** [comment]
Give 3.9 a spin

**Comment by Emillzz45** [comment]
3.9.7 worked flawless for me

**Comment by michalis97500** [comment]
Is the python version changing available tensorflow version?

**Comment by michalis97500** [comment]
Used a wrong version of pip, using pip 19 it worked

**Comment by kyleskom** [comment]
Glad this is resolved.
