### ISSUE TITLE
data interpretation

### ISSUE THREAD

**Issue by egamxmx** [kyleskom/NBA-Machine-Learning-Sports-Betting#397]
I have the following result:

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/6864339/684b97a9-27a8-4374-b4e4-f60eec95b2a9)
![resultado-1](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/6864339/a3384fe2-aa84-4867-b2cb-76fba9691c6d)

Here it shows the Bucks in green with 73%, however on the Kelly scale it says that EV: 66.3 towards the opposing team

**Comment by rajp84** [comment]
Betting on Bucks with -700 odds is not worth it... over time you would lose money, so the expected value is negative.

If however, you take the underdogs, the Grizzlies, with those odds (+520), and a 27% chance of winning with this model, then over time the EV is positive. 

In this specific example, the Grizzlies won 113 to 110, so you would have made nice bank.  

(if you did end up losing, then you would have only lost a small fraction of your bankroll)

**Comment by egamxmx** [comment]
thank you very much for the information, greetings
