### ISSUE TITLE
Match Data Issue

### ISSUE THREAD

**Issue by Apollo324** [kyleskom/NBA-Machine-Learning-Sports-Betting#399]
Not sure where to go from here . . . 

<img width="623" alt="Screenshot 2024-02-19 at 12 01 09 AM" src="https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160442732/a870ad92-bd85-47b5-b56d-094767ba4ae1">

**Comment by Apollo324** [comment]
Yes, this error was after running that file.

**Comment by saqib772** [comment]
I think so because yesterday I run the same Code with update data, Getting Fresh Data till 19 FEB 2024 and Then train models but when I run the main fail, it says No game found for any Sports book.

**Comment by Apollo324** [comment]
what's your email bro?

**Comment by saqib772** [comment]
saqibiqbal27772@gmail.com
