### ISSUE TITLE
No Game found For All SportsBook!

### ISSUE THREAD

**Issue by saqib772** [kyleskom/NBA-Machine-Learning-Sports-Betting#400]
![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/121972215/d0788a12-7ca9-430d-86f7-fbe74ff5766e)
hey, When i run the main file after getting the updated data and then training it with only XGboost because with logistic and Neural Networks there are file errors.

**Comment by Jotamixpy** [comment]
not found?

**Comment by saqib772** [comment]
Yes, the main file gives output of No Games Found.

**Comment by kyleskom** [comment]
Because there were no games on the 19th.

**Comment by saqib772** [comment]
Lmfao, for every date this code is not working.
