### ISSUE TITLE
ERRRO -m Create_Games

### ISSUE THREAD

**Issue by Jotamixpy** [kyleskom/NBA-Machine-Learning-Sports-Betting#402]
ONLY 92% AND THEN THE ERROR
![error](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/75957047/a30d8fb5-3eb3-4fb5-9fed-442041abdd6a)

**Comment by HyakuzaO** [comment]
I have the same problem, can anyone please help?

**Comment by Scandianis** [comment]
Working for me: Adding the following on line 37 in Create_Games.py:

if home_team not in ['Eastern']:

Adjust margin of course for the following code.

Final look:

...
year_count = 0

    for row in odds_df.itertuples():
        home_team = row[3]
        away_team = row[4]
        if home_team not in ['Eastern']:

            date = row[2]
            date_array = date.split('-')
            if not date_array or len(date_array) < 2:
                continue
            year = date_array[0] + '-' + date_array[1]

...

**Comment by HyakuzaO** [comment]
You just modify that part and its works? Only that? Ty btw
