### ISSUE TITLE
Please, help me guys

### ISSUE THREAD

**Issue by HyakuzaO** [kyleskom/NBA-Machine-Learning-Sports-Betting#403]
![error](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160853868/a4f5221b-6a27-4471-a846-dcc1f01b5f7d)

Please guys, i tried everything, ask for help on chatgpt but its useless, can anyone please help me do this working guys? i would love run that script but i try everything but i cant.. please someone help me . im a rookie . ty for all that could help me guys

**Comment by Scandianis** [comment]
Did you try this? It is working for me:

Adding the following on line 37 in Create_Games.py:

if home_team not in ['Eastern']:

Adjust margin of course for the following code.

Final look:

...

for row in odds_df.itertuples():
    home_team = row[3]
    away_team = row[4]
    if home_team not in ['Eastern']:

        date = row[2]
        date_array = date.split('-')
        if not date_array or len(date_array) < 2:
            continue
        year = date_array[0] + '-' + date_array[1]
        month = date_array[2][:2]
        day = date_array[2][2:]
...

**Comment by HyakuzaO** [comment]
Line 34: home_team = row[3]
Line 35: away_team = row[4]
Line 36: 
Line 37: if home_team not in ['Eastern']:
Line 38:     date = row[2]
Line 39:     date_array = date.split('-')
Line 40:     if not date_array or len(date_array) < 2:
Line 41:         continue
        # ... Restante do código que processa a data e outras operações ...


Like this bro?

**Comment by HyakuzaO** [comment]
Will try, aprecciate your help bro, can you give your email bro?

**Comment by HyakuzaO** [comment]
![imagem](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160853868/847b6dd5-96c6-4947-9ee5-d873d2a8597c)
after doing that now i have this error :(

**Comment by HyakuzaO** [comment]
anybody have ideas please?

**Comment by Scandianis** [comment]
Did you run these first?

Get_Data.py

Get_Odds_Data.py

**Comment by HyakuzaO** [comment]
![imagem](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160853868/9426a026-8a60-493e-9256-034102ad1712)
i put the code just like you said

**Comment by Scandianis** [comment]
And the further down it is like this? 

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/23011769/e569d239-aee4-4aff-a538-5d7d36884519)

**Comment by HyakuzaO** [comment]
that part is moded as well? im a rookie in this, i just wanna run that machine learning, 4 days trying and getting always that error. could you paste here or send to me that create_games.py already modified? please, and sorry for any inconvinience but i dont know more what to do :(

**Comment by HyakuzaO** [comment]
![imagem](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160853868/fa8ca5f3-94e3-4c2f-a4d4-e94b94e7c63a)

**Comment by Scandianis** [comment]
Here is the file. Rename from txt to py.
[Create_Games.txt](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/files/14386298/Create_Games.txt)

**Comment by HyakuzaO** [comment]
i will try, many thanks

**Comment by saqib772** [comment]
@HyakuzaO Did you run the main file after getting all the latest data? For me it says no data found for every game

**Comment by HyakuzaO** [comment]
@Scandianis now its reach 100% ... many thanks, now will try next steps

**Comment by saqib772** [comment]
The error you were getting is because of none values intitally, I tried to handle that by following:
![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/121972215/896d569a-e85c-4993-83fd-6d020b2810aa)

**Comment by Jotamixpy** [comment]
Ty bro

**Comment by HyakuzaO** [comment]
Many thanks to all that helped me , special to @Scandianis . Cheers bros

**Comment by mohcly** [comment]
hello guys, please I tried everything you says but ended up with this error:
"Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/src/Process-Data/Create_Games.py", line 60, in <module>
    team_df = pd.read_sql_query(f"select * from \"teams_{year}-{month}-{day}\"", teams_con, index_col="index")
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 486, in read_sql_query
    return pandas_sql.read_query(
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 2328, in read_query
    cursor = self.execute(sql, params)
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/venv/lib/python3.9/site-packages/pandas/io/sql.py", line 2276, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'select * from "teams_2023-24-3-1"': no such table: teams_2023-24-3-1
(venv) (base) mohamedcoulibaly@Mohameds-MacBook-Air Process-Data % 
"

**Comment by Scandianis** [comment]
Solved here:

https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/412

**Comment by HyakuzaO** [comment]
#412

**Comment by mohcly** [comment]
thanks guys, I'm checking it

**Comment by mohcly** [comment]
problem solved thanks a lot.

**Comment by mohcly** [comment]
@Scandianis please I have this problem sometimes, I comes a goes by his own, do you know how to solve this?
"  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/main.py", line 142, in <module>
    main()
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/main.py", line 122, in main
    XGBoost_Runner.xgb_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds, args.kc)
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/src/Predict/XGBoost_Runner.py", line 89, in xgb_runner
    bankroll_fraction_home = bankroll_descriptor + str(kc.calculate_kelly_criterion(home_team_odds[count], ml_predictions_array[count][0][1])) + '%'
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/src/Utils/Kelly_Criterion.py", line 15, in calculate_kelly_criterion
    decimal_odds = american_to_decimal(american_odds)
  File "/Users/mohamedcoulibaly/Desktop/NBA-Machine-Learning-Sports-Betting/src/Utils/Kelly_Criterion.py", line 5, in american_to_decimal
    if american_odds >= 100:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
(venv) (base) mohamedcoulibaly@Mohameds-MacBook-Air NBA-Machine-Learning-Sports-Betting % 
"

**Comment by saqib772** [comment]
@mohcly Same Problem, I'm facing right now from 2 Hours.

**Comment by saqib772** [comment]
I think maybe this is Because there's no NBA game of any sportsbook thats why it is retutning the none values. You can handle the NONE values

**Comment by saqib772** [comment]
The Problem is here:

`
def american_to_decimal(american_odds):
    """
    Converts American odds to decimal odds (European odds).
    """
    **if american_odds >= 100:** ( CHECK FOR NONE VALUES) 
        decimal_odds = (american_odds / 100)
    else:
        decimal_odds = (100 / abs(american_odds))
    return round(decimal_odds, 2)

def calculate_kelly_criterion(american_odds, model_prob):
    """
    Calculates the fraction of the bankroll to be wagered on each bet
    """
    decimal_odds = american_to_decimal(american_odds)
    bankroll_fraction = round((100 * (decimal_odds * model_prob - (1 - model_prob))) / decimal_odds, 2)
    return bankroll_fraction if bankroll_fraction > 0 else 0
`

**Comment by saqib772** [comment]
Try the Following code in SRC> UTILS>Kelly_Criterion.py

def american_to_decimal(american_odds):
    """
    Converts American odds to decimal odds (European odds).
    """
    if american_odds is None:
        return None  # Return None if american_odds is None
    if american_odds >= 100:
        decimal_odds = (american_odds / 100)
    else:
        decimal_odds = (100 / abs(american_odds))
    return round(decimal_odds, 2)

def calculate_kelly_criterion(american_odds, model_prob):
    """
    Calculates the fraction of the bankroll to be wagered on each bet
    """
    decimal_odds = american_to_decimal(american_odds)
    if decimal_odds is None:
        return None  # Return None if decimal_odds is None
    bankroll_fraction = round((100 * (decimal_odds * model_prob - (1 - model_prob))) / decimal_odds, 2)
    return bankroll_fraction if bankroll_fraction > 0 else 0

**Comment by Scandianis** [comment]
The above has been working two months for me.
