### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HyakuzaO** [kyleskom/NBA-Machine-Learning-Sports-Betting#412]
![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160853868/e551f2b2-6a6e-4af2-b565-7fa9a3c6bbe8)

Hello guys, can somente please help me solving this? 
Ty All

**Comment by HyakuzaO** [comment]
Anyone? please guys

**Comment by Twistace** [comment]
Try updating data, seems like it trying to select from unavailable sql

**Comment by HyakuzaO** [comment]
i update data, odds, and the error shows on create games :(

**Comment by HyakuzaO** [comment]
anyone have the same error? this happen only today

**Comment by HyakuzaO** [comment]
![imagem](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160853868/3fc05982-2d69-4ce5-be95-bc7082dc3621)

it give me the results as well, but im not sure why the error comes on create games :(

**Comment by HyakuzaO** [comment]
For some reason there is no table 2023-2023-3-1 in Sql file.. someone can help or tell me how to fix it?

**Comment by Scandianis** [comment]
As this year is a leap year, I think that modifying Get_Data.py and Get_Odds_Data.py like this will resolve the issue:

            if month1 == 2 and day1 > 28:     ->                  if month1 == 2 and day1 > 29:

**Comment by HyakuzaO** [comment]
Can you please give me the file modified? Like i said im a noob on this and dont understand. Can you please give the file mod for that fix? I really apreciate the help that you give me

**Comment by HyakuzaO** [comment]
@Scandianis do you have that insue too?

**Comment by HyakuzaO** [comment]
Im sorry for asking for help All te time but im learning this and some day i Will understand. Like i said i just wanna run the scrit in right way without problems

**Comment by HyakuzaO** [comment]
@Scandianis help please 🙏

**Comment by Scandianis** [comment]
Issue resolved - also saw it.

Here are my files - rename extension from txt to py.

[Get_Data.txt](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/files/14469727/Get_Data.txt)

[Get_Odds_Data.txt](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/files/14469728/Get_Odds_Data.txt)

Note also my modification in Get_Odds_Data:

                if game['home_team'] not in ['Team Stephen A','Team BallIsLife','Team Strictly']:
                
Thank you for pointing out the issue.

**Comment by HyakuzaO** [comment]
I Will test my friend. You are the best

**Comment by HyakuzaO** [comment]
I only add to put your files in my files right?

**Comment by Scandianis** [comment]
**Replace** your files with those here.

**Comment by HyakuzaO** [comment]
I will test and give the feedback. I don't even know how to thank you my friend

**Comment by Jotamixpy** [comment]
ty bro

**Comment by HyakuzaO** [comment]
you are the best @Scandianis , it works. many many ty
