### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by linuxdood** [kyleskom/NBA-Machine-Learning-Sports-Betting#416]
Followed the instructions from the README.md for the setup of the package. Had some errors when installing some of the packages due to 'environment managed externally' messages, but I believe those are worked out and not part of the issue I am having. This is capture is from an Arch Linux setup, and further confirmed with same error on a MacBook.
I get the first 2 parts of the output, but errors for the last part :
![NBA-ML-output](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/25709654/df285b0e-3272-4314-b859-4e801e82d9bb)

Suggestions? I messed around in the code to try and Try/Except trap the error, but without success.

**Comment by saqib772** [comment]
@linuxdood 
Try the Following code in SRC> UTILS>Kelly_Criterion.py

def american_to_decimal(american_odds):
"""
Converts American odds to decimal odds (European odds).
"""
if american_odds is None:
return None # Return None if american_odds is None
if american_odds >= 100:
decimal_odds = (american_odds / 100)
else:
decimal_odds = (100 / abs(american_odds))
return round(decimal_odds, 2)

def calculate_kelly_criterion(american_odds, model_prob):
"""
Calculates the fraction of the bankroll to be wagered on each bet
"""
decimal_odds = american_to_decimal(american_odds)
if decimal_odds is None:
return None # Return None if decimal_odds is None
bankroll_fraction = round((100 * (decimal_odds * model_prob - (1 - model_prob))) / decimal_odds, 2)
return bankroll_fraction if bankroll_fraction > 0 else 0

**Comment by Shanna3229** [comment]
I'm on WSL after getting thrown the "cannot parse keras metadata model" error on windows 10. I was getting the same error as linuxdood once run on WSL so I changed the Kelly_Criterion.py as saqib772 specified. Now I'm getting this: 
![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/18405777/bf40c7ad-8dc7-493a-90f9-14662e38cf31)
I'll start going through the calls to make exceptions tomorrow since it has taken me a while to get to this point tonight, but just wanted to give the update.

**Comment by Scandianis** [comment]
This is working for me:

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/23011769/da51b811-2c1c-46f3-868d-03b6c33f78f2)

**Comment by saqib772** [comment]
@Scandianis Good 💯

**Comment by saqib772** [comment]
@Shanna3229 I think it's because the NBA API is not giving Data for OU odds like if there's no Match then it will give None. That's possible but you can add conditions. So, Next time this will not happen again.

**Comment by linuxdood** [comment]
@Shanna3229 is correct - I also believe now that SOME of the sites are not returning the data or some of the data.
I initially tested with fanduel since draftkings those are the books I use. When they both failed, on a a whim, I tried wynn as well, and it failed with this error as well. So i thought it was code related. After reading @Shanna3229's comment, I tried _every_ book, and low and behold, betmgm, pointsbet and bet_rivers_ny WORKED! It just so happens that I managed to hit the 3 that didn't provide the required data and caused the error.
I have made the code adjustments and now it executes flawlessly - it simply does not provide EV information when the data is incomplete.
SUGGESTION : Perhaps include a statement when displaying the information " *** The EV values are incalculable due to incomplete information from the Odds provider (try another book : fandual, draftkings, betmgm, points bet, wynn, bet_rivers_ny) ***" ?

Thank you for your efforts.

**Comment by linuxdood** [comment]
I am unsure if I should close this issue, not sure if I leave it here to remind to have this code correction merged into the package and if the suggesting of posting a message about incomplete data from Odds provider should be added to output?

Please advise.

Cheers.
-y
