### ISSUE TITLE
No table in sqlite file for 2023-24-3-1 in Create_Games

### ISSUE THREAD

**Issue by rpassaro** [kyleskom/NBA-Machine-Learning-Sports-Betting#422]
Anyone know why there is no table in the sqlite file for 2023-24-3-1 or how I should resolve this? Thanks!
<img width="873" alt="Screenshot 2024-03-15 110616" src="https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/61886601/3d1efee2-7803-4e54-9b42-465d6134a4f3">

**Comment by HyakuzaO** [comment]
@rpassaro Find the solution here #412

**Comment by rpassaro** [comment]
Thank you!
