### ISSUE TITLE
Error Running Script Today

### ISSUE THREAD

**Issue by HyakuzaO** [kyleskom/NBA-Machine-Learning-Sports-Betting#423]
![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/160853868/f7a71f02-d348-45cf-a6ac-6da9a43c089c)

Hello guys, today this error happened for the first time.

Anyone knows how to fix it?

Ty for all that could help me.

Regards Guys 🫡

**Comment by omerkymcu** [comment]
yes I got the same error too

**Comment by Scandianis** [comment]
https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/416

**Comment by HyakuzaO** [comment]
@Scandianis Ty bro. What file did you edit? Many thanks

**Comment by Scandianis** [comment]
Kelly_Criterion.py in src\Utils.

[Kelly_Criterion.txt](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/files/14805009/Kelly_Criterion.txt)

(rename .txt to .py)

**Comment by HyakuzaO** [comment]
@Scandianis You are the best dude. Many thanks my friend

**Comment by thadhutch** [comment]
Seems like the bigger problem is that the odds provider doesn't seem to be working anymore. As you can see in your screenshot all the totals values are 'None'

**Comment by tfasoli2020** [comment]
How to fix on jupyter notebooks?

**Comment by Nikken85** [comment]
> Seems like the bigger problem is that the odds provider doesn't seem to be working anymore. As you can see in your screenshot all the totals values are 'None'

I confirm that I'm also experiencing this issue starting from today: all the values are set to 'None'. Has anyone managed to understand why? How can it be resolved?

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/55053287/2b222794-1503-4c12-8008-f1e82f14a766)

**Comment by Scandianis** [comment]
It seems to be missing data from FanDuel:

...
No fanduel odds data found for game: {'date': '2024-03-30T02:00:00+00:00', 'status': '22:00 ET', 'home_team': 'Sacramento Kings', 'home_team_loc': 'Sacramento', 'home_team_abbr': 'SAC', 'home_team_rank': -1, 'away_team': 'Dallas Mavericks', 'away_team_loc': 'Dallas', 'away_team_abbr': 'DAL', 'away_team_rank': -1, 'home_score': 0, 'away_score': 0, 'home_spread': {}, 'home_spread_odds': {}, 
'away_spread': {}, 'away_spread_odds': {}, 'under_odds': {}, 'over_odds': {}, 'total': {}, 'home_ml': {}, 'away_ml': {}}
...

Could perhaps just be an easter update glitch?

**Comment by thadhutch** [comment]
Its an issue with the sbrscrape package. I tried a few different providers and none of them seem to work. No one should use these predictions while these values are None. If you take a look at the feature importance of the models you will notice that the 'OU' value is #1 on the list

**Comment by thadhutch** [comment]
So the issue isn't actually with the package it's with the website itself. If you go to https://www.sportsbookreview.com/betting-odds/nba-basketball/

You'll see that all the odds for today are null

**Comment by coder4L1** [comment]
Do we just have to wait until the Fanduel API's start working again? @Scandianis solution did work for me but gives the 'None' value outputs as it should as it does in @Nikken85 screenshot. Are we just at the mercy of oddsmakers data?

**Comment by Nikken85** [comment]
> So the issue isn't actually with the package it's with the website itself. If you go to https://www.sportsbookreview.com/betting-odds/nba-basketball/
> 
> You'll see that all the odds for today are null

Ah, okay, that's the reason!! Alright then, so all we have to do is wait for them to fix the issue on sportsbookreview.com! Thank you for the analysis

**Comment by coder4L1** [comment]
> So the issue isn't actually with the package it's with the website itself. If you go to https://www.sportsbookreview.com/betting-odds/nba-basketball/
> 
> You'll see that all the odds for today are null

Where is this website stored in the script? Looks like https://www.sportsline.com/nba/odds/ maybe be an alternative

**Comment by HyakuzaO** [comment]
So this is a problem by fanduel odds?

**Comment by willisj318** [comment]
> > So the issue isn't actually with the package it's with the website itself. If you go to https://www.sportsbookreview.com/betting-odds/nba-basketball/
> > You'll see that all the odds for today are null
> 
> Where is this website stored in the script? Looks like https://www.sportsline.com/nba/odds/ may be an alternative

It's technically not, it is using sbrscrape which uses sbrodds/sportsbookreview

**Comment by HyakuzaO** [comment]
So, no fix? Simply a bug from odds today @Scandianis ?

**Comment by willisj318** [comment]
Yea either wait or alter the code to use a different provider.

**Comment by HyakuzaO** [comment]
Maybe tomorrow will work, lets see.

**Comment by HyakuzaO** [comment]
Let's wait until tomorrow, however, if someone finds a solution, please share it here. Thank you all.

**Comment by bwwessl** [comment]
Why cant we run the script manually though?

**Comment by XZoro-404** [comment]
> > So the issue isn't actually with the package it's with the website itself. If you go to https://www.sportsbookreview.com/betting-odds/nba-basketball/
> > You'll see that all the odds for today are null
> 
> Where is this website stored in the script? Looks like https://www.sportsline.com/nba/odds/ may be an alternative

The problem would be formatting it all the same.

**Comment by HyakuzaO** [comment]
Like we said. Maybe tomorrow will work

**Comment by bwwessl** [comment]
Yeah, hopefully the odds get populated on the src data tomorrow. But what I was asking, was why when I manually input the odds into the script, (simply not passing an odds argument), does the script bomb out? It works fine for over under inputs but not money line odds.

**Comment by Scandianis** [comment]
Just placed bets according to this table - odds from Unibet and Betsson (BO).

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Roald/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Roald/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Team | Odds | Prob. | Bankroll factor | EV
-- | -- | -- | -- | --
Hornets BO | 7.3 | 0.274089 | 0.1401 | 100.0848
Blazers | 8 | 0.203326 | 0.0717 | 62.66105
Timberwolves | 3.25 | 0.438459 | 0.1372 | 42.49905
76ers | 3.85 | 0.362069 | 0.0903 | 39.39667
Thunder | 2.02 | 0.64039 | 0.2243 | 29.35874
Jazz BO | 3.6 | 0.367178 | 0.0986 | 32.18404
Spurs | 4.1 | 0.2799 | 0.0403 | 14.75885
Pistons | 2.4 | 0.465916 | 0.0612 | 11.81987
Nets | 2.35 | 0.486431 | 0.0625 | 14.31131



</body>

</html>

**Comment by coder4L1** [comment]
Somewhat unrelated to this issue, but has anyone trained the model for other US sports? MLB, NFL, etc?
