### ISSUE TITLE
No values for under/over

### ISSUE THREAD

**Issue by dndz0r** [kyleskom/NBA-Machine-Learning-Sports-Betting#428]
What can i do about this? I tried using different bookies with the -odds variable but none seems to work.

I always get no values.

Downloaded new season data and trained model, still doesnt seem to work.

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/62314597/b57570ef-7afa-4d95-9bb7-276f1e30ea73)

**Comment by Scandianis** [comment]
Today:

https://www.nba.com/games?date=2024-04-15 -> No games scheduled

**Comment by dndz0r** [comment]
> Today:
> 
> https://www.nba.com/games?date=2024-04-15 -> No games scheduled

This was done first thing in the morning while yesterdays games werent played yet, he listed all the games just fine but never gave me the over/under values.

**Comment by kyleskom** [comment]
There might not of been odds ready

**Comment by dndz0r** [comment]
I just tried again when theres 1 game live and another one that starts in the next 1 hour and here's the outcome.

![image](https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/62314597/3d2f8bb1-6b35-406c-99c2-d96e40d24854)

**Comment by kyleskom** [comment]
Did fan duel have odds currently up when you ran? Sometimes book close out odds at sometimes

**Comment by dndz0r** [comment]
> Did fan duel have odds currently up when you ran? Sometimes book close out odds at sometimes

Yes.

There's a couple of games today within the next 4 to 6 hours, i tried to make a brand new installation of the project and i keep on getting the same results, i do get ML percentages and Under and Over percentages too, just the Over/Under values are not displayed when i run the script.

**Comment by bklynate** [comment]
<img width="1664" alt="Screenshot 2024-04-21 at 6 42 28 PM" src="https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/assets/4186033/0055cceb-ec6a-4c97-9ad3-8cddba03738d">

I was able to successfully run the program today and get back predictions
