### ISSUE TITLE
Documentation clarification is needed.

### ISSUE THREAD

**Issue by bklynate** [kyleskom/NBA-Machine-Learning-Sports-Betting#432]
After freshly cloning a new repo of NBA-Machine-Learning-Sports-Betting am I assuming correctly we'd need to do the following steps after installing all requirements:

1. cd src/Process-Data
2. python -m Get_Data
3. python -m Get_Odds_Data
4. python -m Create_Games

My follow-up questions are:
 - Do we need to follow the steps every day afterward to ensure our data set is complete?
 - How often do we need to train our models?
 - Should we train our models every time we pull new data? This again leads me back to the question of how often we should be running through the process-data steps.
 
 I would love to contribute more. Is there any desire to open this up to other sports?

**Comment by kyleskom** [comment]
No need to train evert day or every week. Maybe more so early on the season but as the season is progressing less training. Im working on making the data processing much easier and cleaner! Im also thinking about adding baseball soon!

**Comment by fuzmik** [comment]
nice baseball
