### ISSUE TITLE
Can this be created with windows?

### ISSUE THREAD

**Issue by Youngstud4321** [kyleskom/NBA-Machine-Learning-Sports-Betting#458]
im having a lot of issues with it and im wondering if this wasnt coded in windows? sorry im new

**Comment by XZoro-404** [comment]
This project was coded in Python which can be run on windows. Having issues with windows is pretty normal because the version of TensorFlow being used does not play nicely with windows now. The workaround to that is to use WSL2 (Windows Subsystem for Linux) to run the code.

**Comment by Youngstud4321** [comment]
[cid:264bcb06-9658-4c6b-9612-ea6257ee1f61]

Now im here




Austin Youngblood

Seaside Engineering and Surveying, LLC

Hydrographic Surveyor

6575 HWY 189N

Baker, Florida 32531

850.650.9563 Office

850.612.3391 Cell

www.seasllc.net<http://www.seasllc.net/>

[SEAS-Logo-Color 40%]



________________________________

**Comment by kyleskom** [comment]
I developed this on Mac. There shouldn't be any major issues with windows.
