### ISSUE TITLE
Getting odds data stuck

### ISSUE THREAD

**Issue by dminik99** [kyleskom/NBA-Machine-Learning-Sports-Betting#459]
Hi!

So running the command python -m Get_Odds_Data seems to be working until it gets to Getting odds data:  2024-03-27 and it completely stuck here. How can i solve it?

![image](https://github.com/user-attachments/assets/9ac0dc73-7ba2-4aca-8db9-942a11e410fa)

**Comment by NoahGrahamDev** [comment]
This is likely either a network error or a temporary issue from one of the odds providers. Try running again after waiting a few hours.
