### ISSUE TITLE
Any difference for M1? 

### ISSUE THREAD

**Issue by Emillzz45** [kyleskom/NBA-Machine-Learning-Sports-Betting#47]
Ran everything perfect on Windows and Python 3.9.7 

Trying to replicate on a M1 however now running into TensorFlow issues. 

Anything I need to do differently here? 

<img width="980" alt="Screenshot 2022-12-10 at 9 01 31 PM" src="https://user-images.githubusercontent.com/68090693/206883071-10e100f0-a591-4845-bad5-cb8c4a38a8e7.png">

**Comment by kyleskom** [comment]
Yes for m1 there is more. Please follow here to install tensorflow for Apple silicon.
https://developer.apple.com/metal/tensorflow-plugin/

**Comment by Emillzz45** [comment]
Ahhh.. thank you for the quick reply

**Comment by Emillzz45** [comment]
Works like butter.

**Comment by kyleskom** [comment]
Nothing like some butter.
