### ISSUE TITLE
Are this Warnings affecting the calculations?

### ISSUE THREAD

**Issue by plexmax** [kyleskom/NBA-Machine-Learning-Sports-Betting#52]
Hello, when I run the main.py I got this Warnings:
![image](https://user-images.githubusercontent.com/52189464/210947871-2f373acb-9b64-4ab1-9e0e-f7c41a3a73fe.png)

Can somebody help me to fix this on Windows?
Is there any how-to install on Ubuntu 18 or 20 ?

**Comment by kyleskom** [comment]
Does not look like this will affect anything.
[](https://stackoverflow.com/questions/59823283/could-not-load-dynamic-library-cudart64-101-dll-on-tensorflow-cpu-only-install)
