### ISSUE TITLE
Flask Web App Wrong Odds

### ISSUE THREAD

**Issue by kyleskom** [kyleskom/NBA-Machine-Learning-Sports-Betting#55]
Should have been 227. Need to fix / check flask web app UI with right odds / predictions. This is with multiple games and specifically Draftkings.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/15850656/211950989-a391aedd-21af-40f0-a6a9-b710741c0da7.png">

**Comment by kyleskom** [comment]
Noticing this with a few games.

**Comment by nkgilley** [comment]
I think what you are seeing is a result of the caching.  If you restart the flask app you should see the odds update.  We may want to remove or lower the caching.

**Comment by kyleskom** [comment]
I restarted a few times and same thing. Im going to try to duplicate this issue again today.
