### ISSUE TITLE
odds

### ISSUE THREAD

**Issue by Rietums44** [kyleskom/NBA-Machine-Learning-Sports-Betting#58]
I'm getting error if I use other odds except fanduel

Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main()
  File "main.py", line 66, in main
    odds = SbrOddsProvider(sportsbook=args.odds).get_odds()
  File "C:\py\NBA2\src\DataProviders\SbrOddsProvider.py", line 30, in get_odds
    money_line_home_value = game['home_ml'][self.sportsbook]
KeyError: 'pointsbet'

**Comment by kyleskom** [comment]
Can you send the command you used to run, Im not seeing any issues.

**Comment by Rietums44** [comment]
python3 main.py -xgb -odds=pointsbet
Or one of this draftkings, betmgm, caesars, wynn, bet_rivers_ny

**Comment by DimaUndSo** [comment]
Same issue here.
I run this: `!python3 main.py -A -odds=fanduel`
It was working an hour ago. I have changed nothing and then this error appeared after trying to make the call again:
`Traceback (most recent call last):
  File "main.py", line 104, in <module>
    main()
  File "main.py", line 66, in main
    odds = SbrOddsProvider(sportsbook=args.odds).get_odds()
  File "/content/src/DataProviders/SbrOddsProvider.py", line 30, in get_odds
    money_line_home_value = game['home_ml'][self.sportsbook]
KeyError: 'fanduel'`

**Comment by kyleskom** [comment]
Ill take a look and try to recreate this issue.

**Comment by Nightwarrior87** [comment]
i resolved

**Comment by DimaUndSo** [comment]
Works again! Great, thanks!
