### ISSUE TITLE
Retrain model and automatic det odd data

### ISSUE THREAD

**Issue by Laurence-1234** [kyleskom/NBA-Machine-Learning-Sports-Betting#59]
Excause me, I have two questions about this.
First, retrain the model is halpful to improve accuracy, and how to retrain the model. I have run the model in src/Train-Models. But the result seens less obvious.
Second, I got error when I run main.py by input -odds=fanduel. I don't know how the error from.

**Comment by kyleskom** [comment]
1.) What results are you seeing when training models?
2.) What error are you getting and can you share your whole command you used to run.

**Comment by Laurence-1234** [comment]
1.) I  I just run the code and the screen showing "Done" like this, it looks ok
![image](https://user-images.githubusercontent.com/121691885/214536552-549bc643-6071-4f7f-bf52-bb4e419eab86.png)

**Comment by kyleskom** [comment]
That looks normal and no issues.
