### ISSUE TITLE
What format for: Enter under/over for today's games.

### ISSUE THREAD

**Issue by cryptocoinserver** [kyleskom/NBA-Machine-Learning-Sports-Betting#6]
Wow thank you for this interesting project. 
I just wanted to check it out, but i'm not sure how to enter today's games under/over data.

Do you have a example?
It asks me: `Charlotte Hornets vs Houston Rockets: `

**Comment by kyleskom** [comment]
@cryptocoinserver Just click that line and type the under over for that game. Under overs for games can be found online.

**Comment by mohdsaquib74** [comment]
After running the code main.py

output : Charlotte Hornets vs Houston Rockets: ______________________  "how to give input ?"can you please explain by giving an example. 

can you please give a sample command 
about how to enter under over for the game.

**Comment by kyleskom** [comment]
All you have to do is start typing and hit enter. 🙂
