### ISSUE TITLE
Store Data in a Database

### ISSUE THREAD

**Issue by kyleskom** [kyleskom/NBA-Machine-Learning-Sports-Betting#60]
Switch from storing data inside excel sheets to a database. Need to refactor get_data to save to database and refactor to read from database

**Comment by frontero** [comment]
Is there a fix for this coming up? I now get this error:  `saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory`

**Comment by kyleskom** [comment]
This is just a warning a non-issue.

**Comment by AaronSnowden** [comment]
well i think MySQL database is a valid option for this, right

**Comment by kyleskom** [comment]
That is one option. There is a PR open to move to SQLite

**Comment by Marcfeitosa** [comment]
Sorry guys, It might have nothing to do... But I pulled the data from an excel database and there was no 22-23 season there. Is this database updated?
