### ISSUE TITLE
I can't go any further

### ISSUE THREAD

**Issue by Skysafe64** [kyleskom/NBA-Machine-Learning-Sports-Betting#66]
I can't go further as I run "python3 main.py -xgb -odds=fanduel" and i got "python could not be found. execute with no arguments to proceed to the ó l"

**Comment by nickbarmore7** [comment]
Try replacing 'main.py' with the actual file path. That worked for me earlier when I encountered that error.

**Comment by Skysafe64** [comment]
> Essayez de remplacer 'main.py' par le chemin d'accès réel au fichier. Cela a fonctionné pour moi plus tôt lorsque j'ai rencontré cette erreur.

unfortunately I have the same error

**Comment by nickbarmore7** [comment]
I also forgot to put a '!' before 'python3' last time. Did you remember the '!' ?

**Comment by kyleskom** [comment]
Do you have python installed?

**Comment by Skysafe64** [comment]
> Do you have python installed?

Hello yes Python 3.8

**Comment by Skysafe64** [comment]
> I also forgot to put a '!' before 'python3' last time. Did you remember the '!' ?

yes but the command is not recognized

**Comment by kyleskom** [comment]
Trying running locally.

**Comment by Skysafe64** [comment]
it's good it works with python without the 3

**Comment by Skysafe64** [comment]
And now i have this 
![ups](https://user-images.githubusercontent.com/123671403/214999263-9b4f9a97-8d66-40d7-8728-86dd9aece9cd.PNG)

**Comment by Skysafe64** [comment]
I reinstalled tensorflow, but that removed me several requirements like numpy and others, I put them back and made them compatible with others but now I have this. I'm on Windows, python 3.8, AMD CPU and Nvidia GPU. Sorry but i'm newbie ...

**Comment by nickbarmore7** [comment]
@Skysafe64 You misspelled 'Fanduel' after 'odds=' in the original prompt. That could be causing an issue.

**Comment by Skysafe64** [comment]
> @Skysafe64 You misspelled 'Fanduel' after 'odds=' in the original prompt. That could be causing an issue.

you are right ! thank you, i have this now 
![uupss](https://user-images.githubusercontent.com/123671403/215003159-333d06fe-a3e6-4df3-824f-99a10c65e674.PNG)

**Comment by kyleskom** [comment]
That looks right. Closing issue.

**Comment by Skysafe64** [comment]
Thank you @kyleskom ! Just a last question, I can't launch to have it in Web App

**Comment by kyleskom** [comment]
Should be in the readme

**Comment by Skysafe64** [comment]
> Should be in the readme

yes but not working

**Comment by kyleskom** [comment]
Ware you seeing an error or?

**Comment by Skysafe64** [comment]
![image](https://user-images.githubusercontent.com/123671403/215241768-e411efd4-4fb5-4f6f-8f45-459d63cc4b0a.png)

**Comment by Skysafe64** [comment]
i have this when i execute 
cd Flask
flask --debug run

**Comment by kyleskom** [comment]
Try from here
https://stackoverflow.com/questions/37220055/pip-fatal-error-in-launcher-unable-to-create-process-using
