### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Chealol** [kyleskom/NBA-Machine-Learning-Sports-Betting#70]
An error occurred: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main()
  File "main.py", line 62, in main
    odds = SbrOddsProvider(sportsbook=args.odds).get_odds()
  File "/content/src/DataProviders/SbrOddsProvider.py", line 13, in __init__
    self.games = Scoreboard(sport="NBA").games
AttributeError: 'Scoreboard' object has no attribute 'games'

Not sure, what seems to be going on? 

Has the  "sbrscrape" library changed and the "games" attribute is no longer available? 
Or Is there a mistake in the import statement or in the use of the library?

**Comment by doctorerre** [comment]
happening to me too

**Comment by doctorerre** [comment]
![image](https://user-images.githubusercontent.com/79534115/215615700-88f28d87-fede-4fc2-8954-38e2e864850e.png)
