### ISSUE TITLE
backtesting

### ISSUE THREAD

**Issue by MSeba1** [kyleskom/NBA-Machine-Learning-Sports-Betting#76]
Hi! 
I wanted to know few things, from my understanding the odds do not change the % of the calculation of the moneyline winner correct?
Also recent games effect the moneyline prediction correct?
if that's the case i wanted to know if there's a way to get the predictions from the beginning of the season, i wanted to check the algorithm results for the whole current and last year season. just winning percentage (without odds).

**Comment by kyleskom** [comment]
1.) Odds are not used to calculate
2.) Recent games are not used. Only up till training data.
3.) You could grab all the data for the current season and feed it in and compare results to actual games.
