### ISSUE TITLE
PROBLEME ML

### ISSUE THREAD

**Issue by Papito8z** [kyleskom/NBA-Machine-Learning-Sports-Betting#77]
HI when i launch the main.py i have this error message : OSError: No file or directory found at Models/NN_Models/Trained-Model-ML

what is the problem ? thank you

**Comment by kyleskom** [comment]
Are you running this from google Colab?

**Comment by Papito8z** [comment]
No i run with python on my local machine .

Le jeu. 2 févr. 2023 à 23:43, Kyle Skompinski ***@***.***> a
écrit :

**Comment by Papito8z** [comment]
When I run it with Google Colab, I'm stuck at this step 2023-02-02 23:07:40.865838: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero 2023-02-02 23:07:40.866052: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero 2023-02-02 23:07:40.866209: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0 2023-02-02 23:07:40.866257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13805 MB memory: -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5 WARNING: tensorflow: SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), NOT tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory. 

Milwaukee Bucks vs LA Clippers: ..........

**Comment by kyleskom** [comment]
What command are you using to run?

**Comment by Papito8z** [comment]
I try with python , i try with visual code and with double click
