### ISSUE TITLE
Unable to install requirements

### ISSUE THREAD

**Issue by arnav-jain1** [kyleskom/NBA-Machine-Learning-Sports-Betting#78]
I am trying to install the requirements and I keep getting this error. Anyone know why? 
![image](https://user-images.githubusercontent.com/116742881/216752076-20acc813-a396-4a72-aa12-50144390888f.png)

**Comment by arnav-jain1** [comment]
The problem seems to be with Scikit.

**Comment by kyleskom** [comment]
Use python 3.9. Check your version of numpy as well.

**Comment by arnav-jain1** [comment]
Which numpy version should I use?

**Comment by arnav-jain1** [comment]
I am now getting a different error. After installing the requirements it says 
`tensorboard 2.11.2 requires protobuf<4,>=3.9.2, but you'll have protobuf 4.21.12 which is incompatible.`
`tensorflow 2.6.0 requires numpy~=1.19.2, but you'll have numpy 1.24.2 which is incompatible.`
I tried running it anyway and it wouldn't work and I get the error 
`TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.`
with the program being unable to import tensorflow
I then tried changing to numpy version 1.19.2 but that is only downloadable with python 3.6-3.8

**Comment by kyleskom** [comment]
Remove all packages, move to python 3.9 and re install.

**Comment by korre21aek** [comment]
I got the same problem. I removed all packages and used Python 3.9 and same problem.
