### ISSUE TITLE
What to input data after running main.py -xgb??

### ISSUE THREAD

**Issue by mohdsaquib74** [kyleskom/NBA-Machine-Learning-Sports-Betting#8]
when the execution of main.py file completes
it shows team names like
Indiana Pacers vs Washington Wizards : __________
Now what input should i give in this ?
How to give input 
Please show with an example 
that would be very helpful , sir

**Comment by kyleskom** [comment]
This step you need to enter the under over for that corresponding game. Just start typing the under over for that game and hit enter. 🙂
