### ISSUE TITLE
Google Collab issue with grabbing and parsing data

### ISSUE THREAD

**Issue by l2ofl** [kyleskom/NBA-Machine-Learning-Sports-Betting#86]
File "main.py", line 95, in main
    NN_Runner.nn_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds)
  File "/content/src/Predict/NN_Runner.py", line 66, in nn_runner
    ev_home = float(Expected_Value.expected_value(ml_predictions_array[count][0][1], int(home_team_odds[count])))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by l2ofl** [comment]
------------------fanduel odds data------------------
Philadelphia 76ers (None) @ Brooklyn Nets (None)
Denver Nuggets (None) @ Charlotte Hornets (None)
Miami Heat (None) @ Orlando Magic (None)
Indiana Pacers (None) @ Washington Wizards (None)
Utah Jazz (None) @ New York Knicks (None)
San Antonio Spurs (None) @ Atlanta Hawks (None)
Chicago Bulls (None) @ Cleveland Cavaliers (None)
Los Angeles Lakers (None) @ Golden State Warriors (None)
Dallas Mavericks (None) @ Sacramento Kings (None)
---------------XGBoost Model Predictions---------------
Brooklyn Nets (52.1%) vs Philadelphia 76ers: OVER None (98.5%)
Charlotte Hornets vs Denver Nuggets (81.6%): OVER None (96.5%)
Orlando Magic vs Miami Heat (60.3%): OVER None (94.3%)
Washington Wizards (65.5%) vs Indiana Pacers: OVER None (99.2%)
New York Knicks (67.0%) vs Utah Jazz: OVER None (99.5%)
Atlanta Hawks (78.3%) vs San Antonio Spurs: OVER None (99.5%)
Cleveland Cavaliers (76.1%) vs Chicago Bulls: OVER None (98.8%)
Golden State Warriors (66.0%) vs Los Angeles Lakers: OVER None (98.8%)
Sacramento Kings (59.3%) vs Dallas Mavericks: OVER None (98.0%)
--------------------Expected Value---------------------
Brooklyn Nets EV: 0
Philadelphia 76ers EV: 0
Charlotte Hornets EV: 0
Denver Nuggets EV: 0
Orlando Magic EV: 0
Miami Heat EV: 0
Washington Wizards EV: 0
Indiana Pacers EV: 0
New York Knicks EV: 0
Utah Jazz EV: 0
Atlanta Hawks EV: 0
San Antonio Spurs EV: 0
Cleveland Cavaliers EV: 0
Chicago Bulls EV: 0
Golden State Warriors EV: 0
Los Angeles Lakers EV: 0
Sacramento Kings EV: 0
Dallas Mavericks EV: 0
-------------------------------------------------------
------------Neural Network Model Predictions-----------
2023-02-11 01:08:33.701112: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Brooklyn Nets (57.9%) vs Philadelphia 76ers: UNDER None (nan%)
Charlotte Hornets vs Denver Nuggets (82.4%): UNDER None (nan%)
Orlando Magic vs Miami Heat (58.4%): UNDER None (nan%)
Washington Wizards (67.8%) vs Indiana Pacers: UNDER None (nan%)
New York Knicks (73.0%) vs Utah Jazz: UNDER None (nan%)
Atlanta Hawks (81.2%) vs San Antonio Spurs: UNDER None (nan%)
Cleveland Cavaliers (80.5%) vs Chicago Bulls: UNDER None (nan%)
Golden State Warriors (76.0%) vs Los Angeles Lakers: UNDER None (nan%)
Sacramento Kings (64.1%) vs Dallas Mavericks: UNDER None (nan%)
--------------------Expected Value---------------------
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main()
  File "main.py", line 95, in main
    NN_Runner.nn_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds)
  File "/content/src/Predict/NN_Runner.py", line 66, in nn_runner
    ev_home = float(Expected_Value.expected_value(ml_predictions_array[count][0][1], int(home_team_odds[count])))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by kyleskom** [comment]
I am unable to replicate this. Will need more info.

**Comment by l2ofl** [comment]
standby generating a google collab env with it

**Comment by l2ofl** [comment]
https://colab.research.google.com/drive/1ew_yszBVGFWwR4wHaNMPThzOLBal-06G?usp=sharing

**Comment by kyleskom** [comment]
I see now. This is on collab but not when running locally which is where I run.

**Comment by l2ofl** [comment]
Ah, perhaps nba is seeing too many request from the collab ip and blocking it or generating bad data

**Comment by kyleskom** [comment]
I don't think this is related to the dropped column fix.

**Comment by l2ofl** [comment]
I agree just unlucky timing.

**Comment by kyleskom** [comment]
Ill continue to monitor this and maybe someone has a fix.

**Comment by l2ofl** [comment]
Do you know what file its grabbing this from?
NN_Runner.nn_runner(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds)

Curious to see what the data looks like

**Comment by kyleskom** [comment]
`/src/Predict)/NN_Runner.py`

**Comment by l2ofl** [comment]
Yeah its definitely getting scuffed data 

printed these vars

(data, todays_games_uo, frame_ml, games, home_team_odds, away_team_odds)
--------------------data var---------------------
[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]]
--------------------data todays_games_uo---------------------
[None, None, None, None, None, None, None, None, None]
--------------------frame_ml---------------------
   GP  ... PLUS_MINUS_RANK
0  55  ...               5
1  56  ...               3
2  56  ...              21
3  54  ...              25
4  56  ...              16
5  56  ...              30
6  57  ...              17
7  55  ...              24
8  54  ...              14

[9 rows x 104 columns]
--------------------games---------------------
[['Brooklyn Nets', 'Philadelphia 76ers'], ['Charlotte Hornets', 'Denver Nuggets'], ['Orlando Magic', 'Miami Heat'], ['Washington Wizards', 'Indiana Pacers'], ['New York Knicks', 'Utah Jazz'], ['Atlanta Hawks', 'San Antonio Spurs'], ['Cleveland Cavaliers', 'Chicago Bulls'], ['Golden State Warriors', 'Los Angeles Lakers'], ['Sacramento Kings', 'Dallas Mavericks']]
--------------------home_team_odds---------------------
[None, None, None, None, None, None, None, None, None]
--------------------away_team_odds---------------------
[None, None, None, None, None, None, None, None, None]

**Comment by kyleskom** [comment]
Ya I think there could be some block on collab ips

**Comment by l2ofl** [comment]
The thing is it's getting the teams but the game data is wrong those teams aren't playing each other today which would explain why everything else freaks out

**Comment by l2ofl** [comment]
Looks like its getting tomorrows games

**Comment by l2ofl** [comment]
for collab, it thinks its:

! date 
Sat 11 Feb 2023 02:07:33 AM UTC

**Comment by kyleskom** [comment]
I was going to say, again locally its working but am seeing that on collab

**Comment by l2ofl** [comment]
Closing.

Happened same time as your fix because it was passed midnight UTC aka London time which colab uses by default.
what then happens is the odd.args is detected and attempt to sbrprovider which uses datetime.now which sees the day as the current day in london which is a day in the future of US/NBA

adding this before running main.py in colab should fix.

#Set Timezone
!rm /etc/localtime
!ln -s /usr/share/zoneinfo/US/Central /etc/localtime
!date

**Comment by kyleskom** [comment]
Thanks for the update!
