### ISSUE TITLE
`flask run` reports "No module named 'colorama' ERROR in app: Exception on / [GET] 

### ISSUE THREAD

**Issue by 512jay** [kyleskom/NBA-Machine-Learning-Sports-Betting#88]
Basically, the flask part of the app does not work for me. Here I re-installed colorama with pip just before rerunning flask run and the same error results.

```
(env) PS C:\Users\512ja\PycharmProjects\NBA\NBA-Machine-Learning-Sports-Betting\Flask> pip install colorama
Requirement already satisfied: colorama in c:\users\512ja\pycharmprojects\nba\nba-machine-learning-sports-betting\env\lib\site-packages (0.4.6)
(env) PS C:\Users\512ja\PycharmProjects\NBA\NBA-Machine-Learning-Sports-Betting\Flask> flask run           
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'
[2023-02-11 11:44:59,550] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\512ja\PycharmProjects\NBA\NBA-Machine-Learning-Sports-Betting\env\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\512ja\PycharmProjects\NBA\NBA-Machine-Learning-Sports-Betting\env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\512ja\PycharmProjects\NBA\NBA-Machine-Learning-Sports-Betting\env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
    fanduel = fetch_fanduel(ttl_hash=get_ttl_hash())
  File "C:\Users\512ja\PycharmProjects\NBA\NBA-Machine-Learning-Sports-Betting\Flask\app.py", line 13, in fetch_fanduel
    return fetch_game_data(sportsbook="fanduel")
  File "C:\Users\512ja\PycharmProjects\NBA\NBA-Machine-Learning-Sports-Betting\Flask\app.py", line 27, in fetch_game_data
    stdout = subprocess.check_output(cmd, cwd="../").decode()
  File "C:\Users\512ja\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\512ja\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'main.py', '-xgb', '-odds=fanduel']' returned non-zero exit status 1.
127.0.0.1 - - [11/Feb/2023 11:44:59] "GET / HTTP/1.1" 500 -
```
main.py shows no errrors with colorama
![image](https://user-images.githubusercontent.com/1872844/218270571-5660dddc-d5c2-49ac-93d5-f42b7ac3fa5e.png)

**Comment by kyleskom** [comment]
Did you pip install with command line? Are you also running from command line?

**Comment by 512jay** [comment]
Well, I've been running the program for a while, so I just pulled down the new code and pip-installed the additional requirements. Yes, this is from the command line. I could try a completely new install; I'll do that today and see if it resolves.

**Comment by 512jay** [comment]
There has been little impetus to perform this install, but today there is basketball, so I tried it. First scikit-learn 
![image](https://user-images.githubusercontent.com/1872844/221052539-039777ed-0be6-42b3-9d68-6696e0b88f60.png)
and tensorflow 
![image](https://user-images.githubusercontent.com/1872844/221052737-ba1a9562-c774-4e21-9daa-ba5cb87ae61b.png)
 both would not install at the versions specified in the requirements.txt document, so I changed the requirements.txt use the version listed or higher. 
```python
scikit_learn>=1.0
tensorflow>=2.6.0
```
It downloaded tensorflow a few times to determine which version was compatible.
![image](https://user-images.githubusercontent.com/1872844/221054143-3aeeb87e-f4f2-4cd2-8014-4a8ea0480585.png)
Going to go eat this may take a while longer will update later.

**Comment by 512jay** [comment]
Well, I got back from eating, and errors abound, installation unsuccessful.
![image](https://user-images.githubusercontent.com/1872844/221070686-41b308f0-5ca7-4560-84c6-33c5839906b6.png)
Will give it another go some other day.

**Comment by kyleskom** [comment]
What version of python are you using?

**Comment by 512jay** [comment]
Good question. I think it was 3.11
probably should have used 3.8, good catch.

**Comment by treezie** [comment]
Did you resolve this @512jay? I am receiving the same error.

**Comment by 512jay** [comment]
Not yet, haven't tried a complete install with python 3.8 yet.

**Comment by 512jay** [comment]
Ok, trying with python 3.8  it appears as if everything installed without an issue. However:
![image](https://user-images.githubusercontent.com/1872844/222562230-66069eaa-27b5-4328-bbb0-85d287068a80.png)
I have a problem with colorama and I can't get this thing running. Will try again another day.

![image](https://user-images.githubusercontent.com/1872844/222577990-e6b80e17-959c-42d7-be3f-cc5feddab7cb.png)

**Comment by acmeGR** [comment]
same problem with python 3.9

**Comment by betevents** [comment]
> Ok, trying with python 3.8 it appears as if everything installed without an issue. However: ![image](https://user-images.githubusercontent.com/1872844/222562230-66069eaa-27b5-4328-bbb0-85d287068a80.png) I have a problem with colorama and I can't get this thing running. Will try again another day.
> 
> ![image](https://user-images.githubusercontent.com/1872844/222577990-e6b80e17-959c-42d7-be3f-cc5feddab7cb.png)

try
python3 -m pip install colorama

**Comment by mendez97cr** [comment]
Script kitty.
