### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by m1sterob0t** [kyleskom/NBA-Machine-Learning-Sports-Betting#93]
Getting an error when running main.py

  File "C:\Users\18454\OneDrive\Documents\NBA-Machine-Learning-Sports-Betting-master\main.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by aleksa-codes** [comment]
> Getting an error when running main.py
> 
> File "C:\Users\18454\OneDrive\Documents\NBA-Machine-Learning-Sports-Betting-master\main.py", line 3, in import pandas as pd ModuleNotFoundError: No module named 'pandas'

if you are on Windows use `python ...` instead of  `python3 ...`
