### ISSUE TITLE
zsh: segmentation fault  python3 main.py -xgb -odds=fanduel

### ISSUE THREAD

**Issue by DoNotNut** [kyleskom/NBA-Machine-Learning-Sports-Betting#95]
I've tried running this on a mac terminal and keep getting this error code after entering:

python3 main.py -xgb -odds=fanduel 

I don't know how to fix it someone please lead me in the right direction. It's weird because the code runs (it shows the current games for the data) but when it gets to the XGBoost model prediction this pops up: 
zsh segmentation fault python3 main.py -xgb -odds=fanduel 

Thanks

**Comment by kyleskom** [comment]
Can you provide a stack trace?

**Comment by DoNotNut** [comment]
Yeah, this is also accompanied by a problem report for python that is automatically sent to apple. It's saying that python quit unexpectedly.


<img width="821" alt="Screen Shot 2023-02-14 at 5 28 08 PM" src="https://user-images.githubusercontent.com/125407229/218886199-876a66ba-26f2-44bc-b0f0-6c56120cc090.png">
