### ISSUE TITLE
TypeError: Cannot index by location index with a non-integer key

### ISSUE THREAD

**Issue by ronpysui** [kyleskom/NBA-Machine-Learning-Sports-Betting#97]
I'm getting this TypeError, it was working fine 2 days ago

**Team Ryan (None) @ Team Dwyane (None)
Traceback (most recent call last):
File "main.py", line 106, in
main()
File "main.py", line 79, in main
data, todays_games_uo, frame_ml, home_team_odds, away_team_odds = createTodaysGames(games, df, odds)
File "main.py", line 44, in createTodaysGames
home_team_series = df.iloc[team_index_current.get(home_team)]
File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 931, in getitem
return self._getitem_axis(maybe_callable, axis=axis)
File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py", line 1563, in _getitem_axis
raise TypeError("Cannot index by location index with a non-integer key")
TypeError: Cannot index by location index with a non-integer key**
![edw123](https://user-images.githubusercontent.com/55932474/219575424-6e6933fe-4693-477a-9967-50b4ee2d8ba1.JPG)

**Comment by kyleskom** [comment]
Seeing this issue as well. Will look into it today.

**Comment by raynerz** [comment]
May it be related that there are no games to predict ? Sent from my iPhoneOn 17 Feb 2023, at 17:28, Kyle Skompinski ***@***.***> wrote:﻿
Seeing this issue as well. Will look into it today.

**Comment by Skysafe64** [comment]
No game today its ok

**Comment by kyleskom** [comment]
That def might be it. Still shouldn't throwing an error.

**Comment by Skysafe64** [comment]
> C'est peut-être ça. Ne devrait toujours pas lancer une erreur.

![image](https://user-images.githubusercontent.com/123671403/219829540-b7ae7309-c7d8-49f0-b103-f32d7f9adfd0.png)
and this for me, was working 2 days ago too

**Comment by metypes** [comment]
yeah guys, every here and then I find also some bugs and fix them locally (more often than not it is just a data error missing None type, and it was enough for me to skip that match and iterate towards the next one).
Both these errors though depend on the entire dataset retrieved and not just one row unfortunately.
I am afraid something has changed API side on data response  as it is really odd how 2 errors appear within such short time on a whole level.

Will see if I dig deeper and have it working by today as it is also useful for me

**Comment by kyleskom** [comment]
Resolved with #98
