### ISSUE TITLE
I can't resolve these errors

### ISSUE THREAD

**Issue by Skysafe64** [kyleskom/NBA-Machine-Learning-Sports-Betting#99]
![image](https://user-images.githubusercontent.com/123671403/219906107-1e682dab-1f96-41b3-8737-8e223304826d.png)
 
I'm trying to resolve these errors but I can't. Is it really annoying when the matches start again?

Thank you in advance for your answers

**Comment by kyleskom** [comment]
#98

**Comment by Skysafe64** [comment]
I just did it, it doesn't work

**Comment by kyleskom** [comment]
Did you pull on master branch?

**Comment by Skysafe64** [comment]
Yes, here the errors i got :
![image](https://user-images.githubusercontent.com/123671403/219907824-6f989b60-7856-4798-8142-e64219a6826c.png)

**Comment by kyleskom** [comment]
I am not able to recreate this.

**Comment by Skysafe64** [comment]
weird problem no ?
